(in-package #:mine-tests)

(defvar *source-read-marker* nil)

(defun check-package-inspection-does-not-evaluate-source ()
  (let ((*source-read-marker* nil))
    (app::%detect-buffer-package
     "#.(setf mine-tests::*source-read-marker* t) (in-package #:cl-user)"
     "DEFAULT")
    (%check (null *source-read-marker*) "Source inspection executed a reader form")))

(defun check-mailbox-preserves-diagnostic-generations ()
  (let* ((state (%test-state))
         (mailbox (sb-concurrency:make-mailbox))
         (key "buffer://mailbox-regression")
         (diagnostic (list :request 7001 :file key :start 0 :end 1
                           :severity :error :summary "obsolete" :label-kind :primary)))
    (setf (mine/app/state::%native-box-value (mine/app/state:get-proto-mailbox state))
          mailbox)
    (unwind-protect
         (progn
           (mine/app/diagnostics:track-diagnostic-request 7001)
           (mine/app/diagnostics:invalidate-diagnostics-for-file key)
           (%check (mine/app/diagnostics:diagnostic-stale-p diagnostic)
                   "Expected diagnostic to be stale before draining")
           (sb-concurrency:send-message mailbox (list :notify (cons :diagnostic diagnostic)))
           (sb-concurrency:send-message mailbox '(:return 7001 (:ok "done")))
           (app::%drain-and-parse-messages state)
           (%check (null (mine/app/diagnostics:line-diagnostic-spans key 0 2))
                   "A stale diagnostic was restored while draining the mailbox"))
      (mine/app/diagnostics:forget-diagnostic-request 7001)
      (mine/app/diagnostics:clear-diagnostics-for-file key))))

(defun check-mailbox-callbacks-run-in-arrival-order ()
  (let* ((state (%test-state))
         (mailbox (sb-concurrency:make-mailbox))
         (app::*pending-requests* nil)
         (seen nil))
    (setf (mine/app/state::%native-box-value (mine/app/state:get-proto-mailbox state))
          mailbox)
    (dolist (id '(8001 8002))
      (let ((request-id id))
        (app::%register-pending-request
         request-id (lambda (state payload)
                      (declare (ignore state payload))
                      (push request-id seen))))
      (sb-concurrency:send-message mailbox (list :return id '(:ok "done"))))
    (app::%drain-and-parse-messages state)
    (%check (equal '(8001 8002) (reverse seen))
            "Callbacks ran out of arrival order: ~S" (reverse seen))))

(defun check-editor-undo-redo-after-save-is-dirty ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (merge-pathnames "undo.txt" directory))
           (manager (mine/app/state:get-bufmgr state))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file path "base")
      (app::open-loose-file! state (namestring path))
      (let ((buffer (%test-current-buffer state)))
        (ops:insert-string! buffer (buf:buffer-undo buffer) cs "changed-")
        (mine/buffer/manager:bufmgr-save! manager (buf:buffer-id buffer))
        (app::handle-editor-key state (input:KeyCtrl #\z) input:ModNone)
        (%check (string= "base" (gap:gap-to-string (buf:buffer-gap buffer)))
                "Undo did not restore original text")
        (%check (buf:buffer-dirty? buffer) "Undo after save was incorrectly clean")
        (mine/buffer/manager:bufmgr-save! manager (buf:buffer-id buffer))
        (app::handle-editor-key state (input:KeyCtrl #\y) input:ModNone)
        (%check (string= "changed-base" (gap:gap-to-string (buf:buffer-gap buffer)))
                "Redo did not restore changed text")
        (%check (buf:buffer-dirty? buffer) "Redo after save was incorrectly clean")))))

(defun check-preview-keeps-permanently-open-buffer ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (a (namestring (merge-pathnames "a.txt" directory)))
           (b (namestring (merge-pathnames "b.txt" directory))))
      (%write-utf8-file a "aaa")
      (%write-utf8-file b "bbb")
      (app::open-loose-file! state a)
      (let ((original (%test-current-buffer state)))
        (app::tree-open-file! state a)
        (app::tree-open-file! state b)
        (%check (eq original
                    (app::%coalton-optional-value-or-nil
                     (mine/buffer/manager:bufmgr-find-by-path
                      (mine/app/state:get-bufmgr state) a)))
                "Previewing another file closed a permanently open buffer")))))

(defun check-streamed-output-keeps-line-boundaries ()
  (let* ((state (%test-state))
         (pane (mine/app/state:get-repl-pane state)))
    (repl:repl-pane-clear-output! pane)
    (dolist (chunk (list "a" (format nil "b~%") (format nil "~%") "c"))
      (app::handle-proto-msg! state
                             (app::%parse-one-message
                              (list :notify (list :output-chunk 91 chunk)))))
    (repl:repl-pane-append-output! pane "=> result")
    (let ((actual (repl:repl-pane-output-lines pane)))
      (%check (equal '("ab" "" "c" "=> result") actual)
              "Streaming inserted or lost line breaks: ~S" actual))))

(defun check-streamed-output-extends-unfinished-line ()
  (let* ((pane (repl:repl-pane-new))
         (chunks (append (loop :for i :below 1500 :collect (format nil "~36R," i))
                         (list (make-string 5000 :initial-element #\z))
                         (loop :for i :from 1500 :below 3000 :collect (format nil "~36R," i))))
         (line (format nil "~{~A~}" chunks))
         (scr (mine/term/screen:screen-new 8 3)))
    (dolist (chunk chunks)
      (repl:repl-pane-append-output-chunk! pane chunk))
    (let ((snapshot (repl:repl-pane-output-lines pane)))
      (%check (equal (list line) snapshot)
              "Chunks without newlines must accumulate into one exact line")
      (repl:repl-pane-render pane scr (wt:Rect 0 0 8 3))
      (%check (string= (subseq line 0 8)
                       (coerce (loop :for x :below 8
                                     :collect (mine-tests/editor-layout::screen-cell-character scr x 0))
                               'string))
              "The unfinished line must render its current text")
      (repl:repl-pane-start-selection! pane 0 2)
      (repl:repl-pane-extend-selection! pane 0 9)
      (%check (string= (subseq line 2 9) (repl:repl-pane-copy-selection! pane))
              "Selection must copy text from the unfinished line")
      (dolist (chunk (list "a" (format nil "b~%c") "" (format nil "~%") (format nil "d~%~%e") "f"))
        (repl:repl-pane-append-output-chunk! pane chunk))
      (repl:repl-pane-append-output! pane "=> result")
      (let ((actual (repl:repl-pane-output-lines pane)))
        (%check (equal (list (concatenate 'string line "ab") "c" "d" "" "ef" "=> result") actual)
                "Streamed chunks produced ~S" actual))
      (%check (equal (list line) snapshot)
              "Output lines returned earlier changed when more output arrived"))))

(defun check-repl-package-follows-matching-runtime-acknowledgment ()
  (let* ((state (%test-state))
         (package-cell (mine/app/state:get-repl-package-cell state)))
    (coalton/cell:write! (mine/app/state:get-active-request-cell state)
                        (coalton:Some (mine/protocol/messages:RequestId 92)))
    (app::handle-proto-msg! state
                           (app::%parse-one-message '(:notify (:package 91 "stale"))))
    (%check (not (string= "stale" (coalton/cell:read package-cell)))
            "An unrelated request changed the REPL package")
    (app::handle-proto-msg! state
                           (app::%parse-one-message '(:notify (:package 92 "exact-case"))))
    (%check (string= "exact-case" (coalton/cell:read package-cell))
            "Matching package acknowledgment lost exact package identity")))

(defun check-editor-services-use-package-before-cursor ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "packages.lisp" directory)))
           (text (format nil "(in-package :first)~%(target )~%(in-package :second)~%(other )"))
           (terminal (%test-terminal 100 30))
           (seen-hints nil)
           (seen-definitions nil))
      (%write-utf8-file path text)
      (app::open-loose-file! state path)
      (%call-with-replaced-runtime-function
       'app::%request-symbol-hint
       (lambda (state name package)
         (declare (ignore state))
         (push (list name package) seen-hints))
       (lambda ()
         (%call-with-replaced-runtime-function
          'app::%request-remote-definition
          (lambda (state name package path position)
            (declare (ignore state path position))
            (push (list name package) seen-definitions))
          (lambda ()
            (dolist (name '("target" "other"))
              (cursor:cursor-move-to-position! (mine/app/state:get-cursor-state state)
                                               (+ 2 (search name text)))
              (app::render-app state terminal)
              (app::jump-to-definition! state))))))
      (%check (equal '(("target" "FIRST") ("other" "SECOND")) (reverse seen-hints))
              "Hints used package declarations after the cursor: ~S" seen-hints)
      (%check (equal '(("target" "FIRST") ("other" "SECOND")) (reverse seen-definitions))
              "Definition lookup used package declarations after the cursor: ~S" seen-definitions))))

(defun run-app-regression-tests ()
  (dolist (test '(check-package-inspection-does-not-evaluate-source
                  check-mailbox-preserves-diagnostic-generations
                  check-mailbox-callbacks-run-in-arrival-order
                  check-editor-undo-redo-after-save-is-dirty
                  check-preview-keeps-permanently-open-buffer
                  check-streamed-output-keeps-line-boundaries
                  check-streamed-output-extends-unfinished-line
                  check-repl-package-follows-matching-runtime-acknowledgment
                  check-editor-services-use-package-before-cursor))
    (format t "~&~A~%" test)
    (funcall test))
  t)
