(in-package #:mine-tests)

(defvar *source-read-marker* nil)

(defun check-package-inspection-does-not-evaluate-source ()
  (let ((*source-read-marker* nil))
    (app::%detect-buffer-package
     "#.(setf mine-tests::*source-read-marker* t) (in-package #:cl-user)"
     "DEFAULT")
    (%check (null *source-read-marker*) "Source inspection executed a reader form")))

(defun check-mailbox-preserves-diagnostic-generations ()
  (let* ((state (%test-state))
         (mailbox (sb-concurrency:make-mailbox))
         (key "buffer://mailbox-regression")
         (diagnostic (list :request 7001 :file key :start 0 :end 1
                           :severity :error :summary "obsolete" :label-kind :primary)))
    (setf (mine/app/state::%native-box-value (mine/app/state:get-proto-mailbox state))
          mailbox)
    (unwind-protect
         (progn
           (mine/app/diagnostics:track-diagnostic-request 7001)
           (mine/app/diagnostics:invalidate-diagnostics-for-file key)
           (%check (mine/app/diagnostics:diagnostic-stale-p diagnostic)
                   "Expected diagnostic to be stale before draining")
           (sb-concurrency:send-message mailbox (list :notify (cons :diagnostic diagnostic)))
           (sb-concurrency:send-message mailbox '(:return 7001 (:ok "done")))
           (app::process-protocol-messages! state)
           (%check (null (mine/app/diagnostics:line-diagnostic-spans key 0 2))
                   "A stale diagnostic was restored while draining the mailbox"))
      (mine/app/diagnostics:forget-diagnostic-request 7001)
      (mine/app/diagnostics:clear-diagnostics-for-file key))))

(defun check-mailbox-callbacks-run-in-arrival-order ()
  (let* ((state (%test-state))
         (mailbox (sb-concurrency:make-mailbox)))
    (setf (mine/app/state::%native-box-value (mine/app/state:get-proto-mailbox state)) mailbox)
    (coalton/cell:write! (mine/app/state:.ms-active-request state)
                        (coalton:Some (mine/protocol/messages:RequestId 8001)))
    (sb-concurrency:send-message mailbox '(:notify (:package 8001 "first")))
    (sb-concurrency:send-message mailbox '(:notify (:package 8001 "second")))
    (app::process-protocol-messages! state)
    (%check (string= "second" (coalton/cell:read (mine/app/state:get-repl-package-cell state)))
            "Protocol side effects ran out of arrival order")))

(defun check-completion-rejects-changed-origin ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (a (namestring (merge-pathnames "a.lisp" directory)))
           (b (namestring (merge-pathnames "b.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file a "for")
      (%write-utf8-file b "for")
      (app::open-loose-file! state a)
      (cursor:cursor-move-to-position! cs 3)
      (let ((snapshot (app::%coalton-optional-value-or-nil (app::%completion-snapshot state))))
        (app::%register-pending-request state 9001 (mine/app/requests:PendingCompletion snapshot))
        (app::open-loose-file! state b)
        (cursor:cursor-move-to-position! cs 3)
        (app::handle-proto-msg! state (app::%parse-one-message '(:return 9001 (:ok (("format" "fn" ""))))))
        (%check (string= "for" (gap:gap-to-string (buf:buffer-gap (%test-current-buffer state))))
                "A delayed completion edited a different document")
        (app::open-loose-file! state a)
        (app::%register-pending-request state 9002 (mine/app/requests:PendingCompletion snapshot))
        (cursor:cursor-move-to-position! cs 2)
        (app::handle-proto-msg! state (app::%parse-one-message '(:return 9002 (:ok (("format" "fn" ""))))))
        (%check (string= "for" (gap:gap-to-string (buf:buffer-gap (%test-current-buffer state))))
                "A delayed completion ignored cursor movement")))))

(defun check-completion-replaces-reader-spelling ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "escaped.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file path "F\\o")
      (app::open-loose-file! state path)
      (cursor:cursor-move-to-position! cs 3)
      (let ((snapshot (app::%coalton-optional-value-or-nil (app::%completion-snapshot state))))
        (app::%register-pending-request state 9010 (mine/app/requests:PendingCompletion snapshot))
        (app::handle-proto-msg! state (app::%parse-one-message '(:return 9010 (:ok (("|Foobar|" "fn" "")))))))
      (%check (string= "|Foobar|" (gap:gap-to-string (buf:buffer-gap (%test-current-buffer state))))
              "Completion appended a canonical spelling to the raw escaped prefix")
      (ops:undo! (%test-current-buffer state) cs)
      (%check (string= "F\\o" (gap:gap-to-string (buf:buffer-gap (%test-current-buffer state))))
              "Completion was not a single reversible edit"))))

(defun check-debugger-input-transition-and-invalid-restart ()
  (let ((state (%test-state)))
    (coalton/cell:write! (mine/app/state:.ms-active-request state)
                        (coalton:Some (mine/protocol/messages:RequestId 9020)))
    (app::handle-proto-msg! state (app::%parse-one-message '(:io-request 9020 "input")))
    (app::handle-proto-msg! state
       (app::%parse-one-message '(:debug 9020 "Interrupted" ((0 "ABORT" "Abort")) ((0 "frame")))))
    (%check (not (coalton/cell:read (mine/app/state:.ms-io-request-active state)))
            "An interrupted input wait still captured debugger keys")
    (app::dbg-send-restart! state 9)
    (%check (coalton/cell:read (mine/app/state:.ms-debugger-active state))
            "An invalid restart dismissed the debugger")
    (app::handle-proto-msg! state (app::%parse-one-message '(:io-request 9020 "argument")))
    (%check (not (coalton/cell:read (mine/app/state:.ms-debugger-active state)))
            "An interactive restart failed to yield to input")
    (app::handle-proto-msg! state (app::%parse-one-message '(:return 9020 (:error "Aborted."))))
    (%check (not (coalton/cell:read (mine/app/state:.ms-io-request-active state)))
            "A completed request left input mode active")))

(defun check-hint-results-stay-with-their-own-request ()
  (let* ((state (%test-state)) (cache (mine/app/state:get-requests state)))
    (app::%register-pending-request state 9030 (mine/app/requests:PendingHint "old" "CL-USER"))
    (app::%register-pending-request state 9031 (mine/app/requests:PendingHint "new" "CL-USER"))
    (mine/app/requests:request-set-hint-context! cache (coalton:Some (coalton:Tuple "new" "CL-USER")))
    (mine/app/requests:request-set-hint-id! cache (coalton:Some 9031))
    (app::handle-proto-msg! state (app::%parse-one-message '(:return 9031 (:ok "NewType"))))
    (app::handle-proto-msg! state (app::%parse-one-message '(:return 9030 (:ok "OldType"))))
    (%check (string= "new :: NewType" (mine/app/requests:request-hint-text cache))
            "An older hint reply overwrote the current symbol's result")))

(defun check-editor-undo-redo-after-save-is-dirty ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (merge-pathnames "undo.txt" directory))
           (manager (mine/app/state:get-bufmgr state))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file path "base")
      (app::open-loose-file! state (namestring path))
      (let ((buffer (%test-current-buffer state)))
        (ops:insert-string! buffer (buf:buffer-undo buffer) cs "changed-")
        (mine/buffer/manager:bufmgr-save! manager (buf:buffer-id buffer))
        (app::handle-editor-key state (input:KeyCtrl #\z) input:ModNone)
        (%check (string= "base" (gap:gap-to-string (buf:buffer-gap buffer)))
                "Undo did not restore original text")
        (%check (buf:buffer-dirty? buffer) "Undo after save was incorrectly clean")
        (mine/buffer/manager:bufmgr-save! manager (buf:buffer-id buffer))
        (app::handle-editor-key state (input:KeyCtrl #\y) input:ModNone)
        (%check (string= "changed-base" (gap:gap-to-string (buf:buffer-gap buffer)))
                "Redo did not restore changed text")
        (%check (buf:buffer-dirty? buffer) "Redo after save was incorrectly clean")))))

(defun check-preview-keeps-permanently-open-buffer ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (a (namestring (merge-pathnames "a.txt" directory)))
           (b (namestring (merge-pathnames "b.txt" directory))))
      (%write-utf8-file a "aaa")
      (%write-utf8-file b "bbb")
      (app::open-loose-file! state a)
      (let ((original (%test-current-buffer state)))
        (app::tree-open-file! state a)
        (app::tree-open-file! state b)
        (%check (eq original
                    (app::%coalton-optional-value-or-nil
                     (mine/buffer/manager:bufmgr-find-by-path
                      (mine/app/state:get-bufmgr state) a)))
                "Previewing another file closed a permanently open buffer")))))

(defun check-streamed-output-keeps-line-boundaries ()
  (let* ((state (%test-state))
         (pane (mine/app/state:get-repl-pane state))
         (widget (repl::.output pane)))
    (mine/widget/text:text-widget-clear! widget)
    (dolist (chunk (list "a" (format nil "b~%") (format nil "~%") "c"))
      (app::handle-proto-msg! state
                             (app::%parse-one-message
                              (list :notify (list :output-chunk 91 chunk)))))
    (repl:repl-pane-append-output! pane "=> result")
    (let* ((lines (coalton/cell:read (mine/widget/text:.tw-lines widget)))
           (actual (loop for i below (coalton/vector:length lines)
                         collect (coalton/vector:index-unsafe i lines))))
      (%check (equal '("ab" "" "c" "=> result") actual)
              "Streaming inserted or lost line breaks: ~S" actual))))

(defun check-repl-package-follows-matching-runtime-acknowledgment ()
  (let* ((state (%test-state))
         (package-cell (mine/app/state:get-repl-package-cell state)))
    (coalton/cell:write! (mine/app/state:.ms-active-request state)
                        (coalton:Some (mine/protocol/messages:RequestId 92)))
    (app::handle-proto-msg! state
                           (app::%parse-one-message '(:notify (:package 91 "stale"))))
    (%check (not (string= "stale" (coalton/cell:read package-cell)))
            "An unrelated request changed the REPL package")
    (app::handle-proto-msg! state
                           (app::%parse-one-message '(:notify (:package 92 "exact-case"))))
    (%check (string= "exact-case" (coalton/cell:read package-cell))
            "Matching package acknowledgment lost exact package identity")))

(defun run-app-regression-tests ()
  (dolist (test '(check-package-inspection-does-not-evaluate-source
                  check-mailbox-preserves-diagnostic-generations
                  check-mailbox-callbacks-run-in-arrival-order
                  check-completion-rejects-changed-origin
                  check-completion-replaces-reader-spelling
                  check-debugger-input-transition-and-invalid-restart
                  check-hint-results-stay-with-their-own-request
                  check-editor-undo-redo-after-save-is-dirty
                  check-preview-keeps-permanently-open-buffer
                  check-streamed-output-keeps-line-boundaries
                  check-repl-package-follows-matching-runtime-acknowledgment))
    (format t "~&~A~%" test)
    (funcall test))
  t)
