(in-package #:mine-tests)

(defvar *source-read-marker* nil)

(defun check-package-inspection-does-not-evaluate-source ()
  (let ((*source-read-marker* nil))
    (app::%detect-buffer-package
     "#.(setf mine-tests::*source-read-marker* t) (in-package #:cl-user)"
     "DEFAULT")
    (%check (null *source-read-marker*) "Source inspection executed a reader form")))

(defun check-mailbox-preserves-diagnostic-generations ()
  (let* ((state (%test-state))
         (mailbox (sb-concurrency:make-mailbox))
         (key "buffer://mailbox-regression")
         (diagnostic (list ':request 7001 ':file key ':start 0 ':end 1
                           ':severity ':error ':summary "obsolete" ':label-kind ':primary)))
    (setf (mine/app/state::%native-box-value (mine/app/state:get-proto-mailbox state))
          mailbox)
    (unwind-protect
         (progn
           (mine/app/diagnostics:track-diagnostic-request 7001)
           (mine/app/diagnostics:invalidate-diagnostics-for-file key)
           (%check (mine/app/diagnostics:diagnostic-stale-p diagnostic)
                   "Expected diagnostic to be stale before draining")
           (sb-concurrency:send-message mailbox (list ':notify (cons ':diagnostic diagnostic)))
           (sb-concurrency:send-message mailbox '(:return 7001 (:ok "done")))
           (app::process-protocol-messages! state)
           (%check (null (mine/app/diagnostics:line-diagnostic-spans key 0 2))
                   "A stale diagnostic was restored while draining the mailbox"))
      (mine/app/diagnostics:forget-diagnostic-request 7001)
      (mine/app/diagnostics:clear-diagnostics-for-file key))))

(defun check-mailbox-callbacks-run-in-arrival-order ()
  (let* ((state (%test-state))
         (mailbox (sb-concurrency:make-mailbox)))
    (setf (mine/app/state::%native-box-value (mine/app/state:get-proto-mailbox state)) mailbox)
    (coalton/cell:write! (mine/app/state:get-active-request-cell state)
                        (coalton:Some (mine/protocol/messages:RequestId 8001)))
    (sb-concurrency:send-message mailbox '(:notify (:package 8001 "first")))
    (sb-concurrency:send-message mailbox '(:notify (:package 8001 "second")))
    (app::process-protocol-messages! state)
    (%check (string= "second" (coalton/cell:read (mine/app/state:get-repl-package-cell state)))
            "Protocol side effects ran out of arrival order")))

(defun check-completion-rejects-changed-origin ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (a (namestring (merge-pathnames "a.lisp" directory)))
           (b (namestring (merge-pathnames "b.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file a "for")
      (%write-utf8-file b "for")
      (app::open-loose-file! state a)
      (cursor:cursor-move-to-position! cs 3)
      (let ((snapshot (app::%coalton-optional-value-or-nil (app::%completion-snapshot state))))
        (app::%register-pending-request state 9001 (mine/app/requests:PendingCompletion snapshot))
        (app::open-loose-file! state b)
        (cursor:cursor-move-to-position! cs 3)
        (app::handle-proto-msg! state (app::%parse-one-message '(:return 9001 (:ok (("format" "fn" ""))))))
        (%check (string= "for" (gap:gap-to-string (buf:buffer-gap (%test-current-buffer state))))
                "A delayed completion edited a different document")
        (app::open-loose-file! state a)
        (app::%register-pending-request state 9002 (mine/app/requests:PendingCompletion snapshot))
        (cursor:cursor-move-to-position! cs 2)
        (app::handle-proto-msg! state (app::%parse-one-message '(:return 9002 (:ok (("format" "fn" ""))))))
        (%check (string= "for" (gap:gap-to-string (buf:buffer-gap (%test-current-buffer state))))
                "A delayed completion ignored cursor movement")))))

(defun check-completion-replaces-reader-spelling ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "escaped.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file path "F\\o")
      (app::open-loose-file! state path)
      (cursor:cursor-move-to-position! cs 3)
      (let ((snapshot (app::%coalton-optional-value-or-nil (app::%completion-snapshot state))))
        (app::%register-pending-request state 9010 (mine/app/requests:PendingCompletion snapshot))
        (app::handle-proto-msg! state (app::%parse-one-message '(:return 9010 (:ok (("|Foobar|" "fn" "")))))))
      (%check (string= "|Foobar|" (gap:gap-to-string (buf:buffer-gap (%test-current-buffer state))))
              "Completion appended a canonical spelling to the raw escaped prefix")
      (ops:undo! (%test-current-buffer state) cs)
      (%check (string= "F\\o" (gap:gap-to-string (buf:buffer-gap (%test-current-buffer state))))
              "Completion was not a single reversible edit"))))

(defun check-debugger-input-transition-and-invalid-restart ()
  (let ((state (%test-state)))
    (coalton/cell:write! (mine/app/state:get-active-request-cell state)
                        (coalton:Some (mine/protocol/messages:RequestId 9020)))
    (app::handle-proto-msg! state (app::%parse-one-message '(:io-request 9020 "input")))
    (app::handle-proto-msg! state
       (app::%parse-one-message '(:debug 9020 "Interrupted" ((0 "ABORT" "Abort")) ((0 "frame")))))
    (%check (not (coalton/cell:read (mine/app/state:get-io-request-active-cell state)))
            "An interrupted input wait still captured debugger keys")
    (app::dbg-send-restart! state 9)
    (%check (coalton/cell:read (mine/app/state:get-debugger-active-cell state))
            "An invalid restart dismissed the debugger")
    (app::handle-proto-msg! state (app::%parse-one-message '(:io-request 9020 "argument")))
    (%check (not (coalton/cell:read (mine/app/state:get-debugger-active-cell state)))
            "An interactive restart failed to yield to input")
    (app::handle-proto-msg! state (app::%parse-one-message '(:return 9020 (:error "Aborted."))))
    (%check (not (coalton/cell:read (mine/app/state:get-io-request-active-cell state)))
            "A completed request left input mode active")))

(defun check-hint-results-stay-with-their-own-request ()
  (let* ((state (%test-state)) (cache (mine/app/state:get-requests state)))
    (app::%register-pending-request state 9030 (mine/app/requests:PendingHint "old" "CL-USER"))
    (app::%register-pending-request state 9031 (mine/app/requests:PendingHint "new" "CL-USER"))
    (mine/app/requests:request-set-hint-context! cache (coalton:Some (coalton-prelude:Tuple "new" "CL-USER")))
    (mine/app/requests:request-set-hint-id! cache (coalton:Some 9031))
    (app::handle-proto-msg! state (app::%parse-one-message '(:return 9031 (:ok "NewType"))))
    (app::handle-proto-msg! state (app::%parse-one-message '(:return 9030 (:ok "OldType"))))
    (%check (string= "new :: NewType" (mine/app/requests:request-hint-text cache))
            "An older hint reply overwrote the current symbol's result")))

(defun check-editor-undo-redo-after-save-is-dirty ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (merge-pathnames "undo.txt" directory))
           (manager (mine/app/state:get-bufmgr state))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file path "base")
      (app::open-loose-file! state (namestring path))
      (let ((buffer (%test-current-buffer state)))
        (ops:insert-string! buffer (buf:buffer-undo buffer) cs "changed-")
        (mine/buffer/manager:bufmgr-save! manager (buf:buffer-id buffer))
        (app::handle-editor-key state (input:KeyCtrl #\z) input:ModNone)
        (%check (string= "base" (gap:gap-to-string (buf:buffer-gap buffer)))
                "Undo did not restore original text")
        (%check (buf:buffer-dirty? buffer) "Undo after save was incorrectly clean")
        (mine/buffer/manager:bufmgr-save! manager (buf:buffer-id buffer))
        (app::handle-editor-key state (input:KeyCtrl #\y) input:ModNone)
        (%check (string= "changed-base" (gap:gap-to-string (buf:buffer-gap buffer)))
                "Redo did not restore changed text")
        (%check (buf:buffer-dirty? buffer) "Redo after save was incorrectly clean")))))

(defun check-editor-delete-keys-remove-selection ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "selection.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file path "(alpha beta gamma)")
      (app::open-loose-file! state path)
      (let ((buffer (%test-current-buffer state)))
        (flet ((text () (gap:gap-to-string (buf:buffer-gap buffer)))
               (select (anchor point)
                 (cursor:cursor-move-to-position! cs anchor)
                 (cursor:cursor-start-selection! cs)
                 (cursor:cursor-move-to-position! cs point)))
          (select 7 12)
          (app::handle-editor-key state input:KeyDelete input:ModNone)
          (%check (and (string= "(alpha gamma)" (text)) (= 7 (cursor:cursor-position cs)))
                  "Delete did not remove a forward selection: ~S" (text))
          (%check (coalton-impl/runtime/optional:cl-none-p (cursor:cursor-selection-anchor cs))
                  "Deleting a selection left it active")
          (select 12 7)
          (app::handle-editor-key state input:KeyBackspace input:ModNone)
          (%check (and (string= "(alpha )" (text)) (= 7 (cursor:cursor-position cs)))
                  "Backspace did not remove a backward selection: ~S" (text))
          (ops:undo! buffer cs)
          (%check (string= "(alpha gamma)" (text))
                  "Undo did not restore a deleted selection in one step: ~S" (text))
          (select 1 1)
          (app::handle-editor-key state input:KeyDelete input:ModNone)
          (%check (string= "(lpha gamma)" (text))
                  "Delete with an empty selection did not delete one character: ~S" (text)))))))

(defun check-editor-paste-replaces-selection ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "paste.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file path "(alpha beta gamma)")
      (app::open-loose-file! state path)
      (let ((buffer (%test-current-buffer state)))
        (flet ((text () (gap:gap-to-string (buf:buffer-gap buffer)))
               (paste ()
                 (%call-with-replaced-runtime-function
                  'mine/app/clipboard::%clipboard-paste (lambda () "XYZ")
                  (lambda ()
                    (app::handle-editor-key state (input:KeyCtrl #\v) input:ModNone)))))
          (cursor:cursor-move-to-position! cs 11)
          (cursor:cursor-start-selection! cs)
          (cursor:cursor-move-to-position! cs 7)
          (paste)
          (%check (and (string= "(alpha XYZ gamma)" (text)) (= 10 (cursor:cursor-position cs)))
                  "Paste did not replace the selection: ~S" (text))
          (%check (coalton-impl/runtime/optional:cl-none-p (cursor:cursor-selection-anchor cs))
                  "Paste left the replaced selection active")
          (ops:undo! buffer cs)
          (%check (string= "(alpha beta gamma)" (text))
                  "Undo did not restore a replaced selection in one step: ~S" (text))
          (cursor:cursor-move-to-position! cs 1)
          (paste)
          (%check (string= "(XYZalpha beta gamma)" (text))
                  "Paste without a selection did not insert at the cursor: ~S" (text)))))))

(defun check-preview-keeps-permanently-open-buffer ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (a (namestring (merge-pathnames "a.txt" directory)))
           (b (namestring (merge-pathnames "b.txt" directory))))
      (%write-utf8-file a "aaa")
      (%write-utf8-file b "bbb")
      (app::open-loose-file! state a)
      (let ((original (%test-current-buffer state)))
        (app::tree-open-file! state a)
        (app::tree-open-file! state b)
        (%check (eq original
                    (app::%coalton-optional-value-or-nil
                     (mine/buffer/manager:bufmgr-find-by-path
                      (mine/app/state:get-bufmgr state) a)))
                "Previewing another file closed a permanently open buffer")))))

(defun check-streamed-output-keeps-line-boundaries ()
  (let* ((state (%test-state))
         (pane (mine/app/state:get-repl-pane state)))
    (repl:repl-pane-clear-output! pane)
    (dolist (chunk (list "a" (format nil "b~%") (format nil "~%") "c"))
      (app::handle-proto-msg! state
                             (app::%parse-one-message
                              (list ':notify (list ':output-chunk 91 chunk)))))
    (repl:repl-pane-append-output! pane "=> result")
    (let ((actual (repl:repl-pane-output-lines pane)))
      (%check (equal '("ab" "" "c" "=> result") actual)
              "Streaming inserted or lost line breaks: ~S" actual))))

(defun check-streamed-output-extends-unfinished-line ()
  (let* ((pane (repl:repl-pane-new))
         (chunks (append (loop :for i :below 1500 :collect (format nil "~36R," i))
                         (list (make-string 5000 :initial-element #\z))
                         (loop :for i :from 1500 :below 3000 :collect (format nil "~36R," i))))
         (line (format nil "~{~A~}" chunks))
         (scr (mine/term/screen:screen-new 8 3)))
    (dolist (chunk chunks)
      (repl:repl-pane-append-output-chunk! pane chunk))
    (let ((snapshot (repl:repl-pane-output-lines pane)))
      (%check (equal (list line) snapshot)
              "Chunks without newlines must accumulate into one exact line")
      (repl:repl-pane-render pane scr (wt:Rect 0 0 8 3))
      (%check (string= (subseq line 0 8)
                       (coerce (loop :for x :below 8
                                     :collect (mine-tests/editor-layout::screen-cell-character scr x 0))
                               'string))
              "The unfinished line must render its current text")
      (repl:repl-pane-start-selection! pane 0 2)
      (repl:repl-pane-extend-selection! pane 0 9)
      (%check (string= (subseq line 2 9) (repl:repl-pane-copy-selection! pane))
              "Selection must copy text from the unfinished line")
      (dolist (chunk (list "a" (format nil "b~%c") "" (format nil "~%") (format nil "d~%~%e") "f"))
        (repl:repl-pane-append-output-chunk! pane chunk))
      (repl:repl-pane-append-output! pane "=> result")
      (let ((actual (repl:repl-pane-output-lines pane)))
        (%check (equal (list (concatenate 'string line "ab") "c" "d" "" "ef" "=> result") actual)
                "Streamed chunks produced ~S" actual))
      (%check (equal (list line) snapshot)
              "Output lines returned earlier changed when more output arrived"))))

(defun check-repl-package-follows-matching-runtime-acknowledgment ()
  (let* ((state (%test-state))
         (package-cell (mine/app/state:get-repl-package-cell state)))
    (coalton/cell:write! (mine/app/state:get-active-request-cell state)
                        (coalton:Some (mine/protocol/messages:RequestId 92)))
    (app::handle-proto-msg! state
                           (app::%parse-one-message '(:notify (:package 91 "stale"))))
    (%check (not (string= "stale" (coalton/cell:read package-cell)))
            "An unrelated request changed the REPL package")
    (app::handle-proto-msg! state
                           (app::%parse-one-message '(:notify (:package 92 "exact-case"))))
    (%check (string= "exact-case" (coalton/cell:read package-cell))
            "Matching package acknowledgment lost exact package identity")))

(defun check-editor-services-use-package-before-cursor ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "packages.lisp" directory)))
           (text (format nil "(in-package :first)~%(target )~%(in-package :second)~%(other )"))
           (terminal (%test-terminal 100 30))
           (seen-hints nil)
           (seen-definitions nil))
      (%write-utf8-file path text)
      (app::open-loose-file! state path)
      (%call-with-replaced-runtime-function
       'app::%request-symbol-hint
       (lambda (state name package)
         (declare (ignore state))
         (push (list name package) seen-hints))
       (lambda ()
         (%call-with-replaced-runtime-function
          'app::%request-remote-definition
          (lambda (state name package path position)
            (declare (ignore state path position))
            (push (list name package) seen-definitions))
          (lambda ()
            (dolist (name '("target" "other"))
              (cursor:cursor-move-to-position! (mine/app/state:get-cursor-state state)
                                               (+ 2 (search name text)))
              (app::render-app state terminal)
              (app::jump-to-definition! state))))))
      (%check (equal '(("target" "FIRST") ("other" "SECOND")) (reverse seen-hints))
              "Hints used package declarations after the cursor: ~S" seen-hints)
      (%check (equal '(("target" "FIRST") ("other" "SECOND")) (reverse seen-definitions))
              "Definition lookup used package declarations after the cursor: ~S" seen-definitions))))

(defun check-definition-response-reuses-compiled-document ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "definition.lisp" directory)))
           (caller-path (namestring (merge-pathnames "caller.lisp" directory)))
           (mine/app/diagnostics::*diagnostic-store*
             (mine/app/diagnostic-store:diagnostic-store-new)))
      (%write-utf8-file path "(defun target () 42)")
      (%write-utf8-file caller-path "(target)")
      (app::open-loose-file! state path)
      (let ((buffer (%test-current-buffer state))
            (cursor (mine/app/state:get-cursor-state state)))
        (ops:insert-string! buffer (buf:buffer-undo buffer) cursor
                            (format nil ";; unsaved~%"))
        (let* ((snapshot (gap:gap-to-string (buf:buffer-gap buffer)))
               (offset (search "(defun" snapshot))
               (temporary (mine/app/diagnostics:write-temp-for-compile
                           snapshot (buf:buffer-document-key buffer))))
          (unwind-protect
               (progn
                 (mine/app/diagnostics:track-diagnostic-request 9120)
                 (mine/app/diagnostics:forget-diagnostic-request 9120)
                 (%check (not (probe-file temporary)) "Finished compile retained its snapshot")
                 (app::open-loose-file! state caller-path)
                 (let ((caller (%test-current-buffer state)))
                   (cursor:cursor-move-to-position! cursor 2)
                   (app::%apply-definition-response
                    state
                    (mine/app/requests:SourceLocation (buf:buffer-document-key caller) 2)
                    (list ':ok (list (list (cons ':file temporary) (cons ':offset offset)))))
                   (%check (eq buffer (%test-current-buffer state))
                           "Definition lookup opened a snapshot instead of reusing its document")
                   (%check (and (buf:buffer-dirty? buffer)
                                (string= snapshot (gap:gap-to-string (buf:buffer-gap buffer))))
                           "Definition lookup replaced unsaved edits")
                   (%check (= offset (cursor:cursor-position cursor))
                           "Definition lookup lost the compiled character offset")
                   (%check (null (app::%coalton-optional-value-or-nil
                                  (mine/buffer/manager:bufmgr-find-by-path
                                   (mine/app/state:get-bufmgr state) temporary)))
                           "Definition lookup created an empty snapshot buffer")
                   (app::jump-back! state)
                   (%check (and (eq caller (%test-current-buffer state))
                                (= 2 (cursor:cursor-position cursor)))
                           "Jump back did not restore the calling document")))
            (mine/app/diagnostics:forget-all-diagnostic-requests)))))))

(defun check-runtime-session-shutdown-releases-compile-temporaries ()
  (dolist (exit '(:return :throw :error))
    (let* ((state (%test-state))
           (mine/app/diagnostics::*diagnostic-store*
             (mine/app/diagnostic-store:diagnostic-store-new))
           (temporary nil)
           (pending nil)
           (stopped nil)
           (failure (make-condition 'simple-error :format-control "Expected TUI failure")))
      (unwind-protect
           (progn
             (setf temporary (mine/app/diagnostics:write-temp-for-compile "(owned)" "buffer://1"))
             (mine/app/diagnostics:track-diagnostic-request 9130)
             (setf pending (mine/app/diagnostics:write-temp-for-compile "(pending)" "buffer://2"))
             (dolist (file (list temporary pending))
               (%write-utf8-file (compile-file-pathname file) "private output"))
             (%call-with-replaced-runtime-function
              'mine/protocol/lifecycle::%runtime-do-stop
              (lambda (manager)
                (%check (eq manager (mine/app/state:get-runtime-mgr state))
                        "Shutdown stopped the wrong runtime")
                (dolist (file (list temporary pending))
                  (%check (and (probe-file file) (probe-file (compile-file-pathname file)))
                          "Shutdown deleted compile files before stopping the runtime"))
                (setf stopped t))
              (lambda ()
                (let ((result
                        (handler-case
                            (catch 'tui-exit
                              (app::%call-with-runtime-session
                               state
                               (lambda ()
                                 (ecase exit
                                   (:return ':return)
                                   (:throw (throw 'tui-exit ':throw))
                                   (:error (error failure))))))
                          (error (condition)
                            (if (eq condition failure) ':error (error condition))))))
                  (%check (eq exit result) "Shutdown changed the session's exit outcome"))))
             (%check stopped "Shutdown did not stop the runtime")
             (dolist (file (list temporary pending))
               (%check (not (probe-file file)) "Shutdown leaked a compile input on ~S" exit)
               (%check (not (probe-file (compile-file-pathname file)))
                       "Shutdown leaked a compiled output on ~S" exit)
               (%check (string= (mine/app/diagnostics::normalize-document-key file)
                                (mine/app/diagnostics:remap-runtime-source-filepath file))
                       "Shutdown retained a runtime source alias"))
             (%check (zerop (mine/app/diagnostic-store:store-request-count
                             mine/app/diagnostics::*diagnostic-store*))
                     "Shutdown retained diagnostic requests")
             (%check (null (mine/app/diagnostic-store:store-pending-temporary-files
                           mine/app/diagnostics::*diagnostic-store*))
                     "Shutdown retained pending compile inputs"))
        (mine/app/diagnostics:forget-all-diagnostic-requests)))))

(defun run-app-regression-tests ()
  (dolist (test '(check-package-inspection-does-not-evaluate-source
                  check-mailbox-preserves-diagnostic-generations
                  check-mailbox-callbacks-run-in-arrival-order
                  check-completion-rejects-changed-origin
                  check-completion-replaces-reader-spelling
                  check-debugger-input-transition-and-invalid-restart
                  check-hint-results-stay-with-their-own-request
                  check-editor-undo-redo-after-save-is-dirty
                  check-editor-delete-keys-remove-selection
                  check-editor-paste-replaces-selection
                  check-preview-keeps-permanently-open-buffer
                  check-streamed-output-keeps-line-boundaries
                  check-streamed-output-extends-unfinished-line
                  check-repl-package-follows-matching-runtime-acknowledgment
                  check-definition-response-reuses-compiled-document
                  check-runtime-session-shutdown-releases-compile-temporaries
                  check-editor-services-use-package-before-cursor))
    (format t "~&~A~%" test)
    (funcall test))
  t)
