(in-package #:mine-tests)

(defun check-preview-retains-identity-until-replacement-opens ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (a (namestring (merge-pathnames "preview.lisp" directory)))
           (bad (namestring (merge-pathnames "unreadable.lisp" directory)))
           (b (namestring (merge-pathnames "next.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file a "original")
      (%write-utf8-file b "next")
      (with-open-file (stream bad :direction ':output :element-type '(unsigned-byte 8))
        (write-byte #xff stream))
      (app::tree-open-file! state a)
      (let ((original (%test-current-buffer state)))
        (cursor:cursor-move-to-position! cs 3)
        (app::tree-open-file! state a)
        (%check (and (eq original (%test-current-buffer state))
                     (= 3 (cursor:cursor-position cs)))
                "Reselecting the preview reloaded its document/view")
        (app::tree-open-file! state bad)
        (%check (eq original (%test-current-buffer state))
                "A failed preview read closed the previous document")
        (ops:insert-string! original (buf:buffer-undo original) cs "edited")
        (app::tree-open-file! state b)
        (%check (eq original
                    (app::%coalton-optional-value-or-nil
                     (mine/buffer/manager:bufmgr-find-by-path (mine/app/state:get-bufmgr state) a)))
                "Changing previews discarded an edited document")
        (%check (find (app::%coalton-optional-value-or-nil (buf:buffer-path original))
                      (mine/pane/tree:tree-pane-open-files (mine/app/state:get-tree-pane state))
                      :key #'coalton-prelude:snd :test #'string=)
                "An edited preview was kept in memory but missing from open files")))))

(defun check-range-indentation-batches-metadata-and-preserves-literals ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "indent.lisp" directory)))
           (calls nil))
      (%write-utf8-file path (format nil "(let ((x \"first~%    literal\"))~%(list x))"))
      (app::open-loose-file! state path)
      (let ((buffer (%test-current-buffer state)))
        (%call-with-replaced-runtime-function
         'app::%request-indent-rules
         (lambda (state heads package &optional timeout)
           (declare (ignore state timeout))
           (push (list heads package) calls)
           nil)
         (lambda ()
           (app::%reindent-line-range! state buffer (buf:buffer-undo buffer)
                                      (mine/app/state:get-cursor-state state) 0 2)))
        (%check (= 1 (length calls)) "Range indentation made ~D metadata queries" (length calls))
        (%check (string= "CL-USER" (second (first calls))) "Wrong default indentation package")
        (%check (search (format nil "\"first~%    literal\"")
                        (gap:gap-to-string (buf:buffer-gap buffer)))
                "Range indentation changed string contents")))))

(defun check-metadata-wait-has-a-deadline ()
  (%call-with-runtime-process
   (lambda (manager)
     (let* ((state (%test-state))
            (runtime (mine/app/state:get-runtime-mgr state)))
       (setf (mine/protocol/lifecycle::%runtime-manager-process runtime)
             (mine/protocol/lifecycle::%runtime-manager-process manager)
             (mine/protocol/lifecycle::%runtime-manager-port runtime)
             (mine/protocol/lifecycle::%runtime-manager-port manager))
       (let* ((started (get-internal-real-time))
              (reply (app::%sync-runtime-request
                      state (mine/protocol/messages:ReqEval
                             (mine/protocol/messages:RequestId 501)
                             "(sleep 3)" "CL-USER" coalton:False)
                      0.03)))
         (%check (null reply) "A slow metadata connection did not time out")
         (%check (< (/ (- (get-internal-real-time) started) internal-time-units-per-second) 2)
                 "Editor metadata blocked waiting for the runtime"))))))

(defun run-app-workflow-extra-tests ()
  (dolist (test '(check-preview-retains-identity-until-replacement-opens
                  check-range-indentation-batches-metadata-and-preserves-literals
                  check-metadata-wait-has-a-deadline))
    (format t "~&~A~%" test)
    (funcall test))
  t)
