(defpackage #:mine-tests/diagnostic-store
  (:use #:cl)
  (:local-nicknames (#:store #:mine/app/diagnostic-store))
  (:export #:run-diagnostic-store-tests))

(in-package #:mine-tests/diagnostic-store)

(defun diagnostic (&key (file "buffer://1") (start 1) (end 4)
                        (severity store:DiagnosticWarning) (kind store:PrimaryLabel)
                        (summary "message") request group)
  (store:Diagnostic file start end severity summary summary kind
                    (if request (coalton:Some request) coalton:None)
                    (if group (coalton:Some group) coalton:None)))

(defun run-diagnostic-store-tests ()
  (let ((store (store:diagnostic-store-new)))
    (store:store-track-request! store 1)
    (store:store-track-request! store 2)
    (assert (store:store-add! store (diagnostic :request 2 :summary "newer")))
    (assert (store:store-stale? store (diagnostic :request 1)))
    (assert (not (store:store-add! store (diagnostic :request 1))))
    (assert (equal "newer" (store:diagnostic-summary (first (store:store-for-file store "buffer://1")))))
    (store:store-clear-file! store "buffer://1")
    (assert (store:store-stale? store (diagnostic :request 2)))
    (store:store-track-request! store 3)
    (assert (store:store-add! store (diagnostic :request 3)))
    (store:store-forget-request! store 3)
    (assert (store:store-stale? store (diagnostic :request 3)))
    (assert (= 1 (length (store:store-for-file store "buffer://1"))))
    (store:store-clear-all! store)
    (assert (null (store:store-all store)))
    (assert (= 2 (store:store-request-count store)))
    (assert (store:store-stale? store (diagnostic :request 2)))
    (store:store-forget-request! store 1)
    (store:store-forget-request! store 2)
    (assert (zerop (store:store-request-count store))))
  (let ((store (store:diagnostic-store-new)))
    (dotimes (id 100)
      (store:store-track-request! store id)
      (assert (store:store-announcement! store (diagnostic :request id :group 0)))
      (assert (not (store:store-announcement! store (diagnostic :request id :group 0))))
      (assert (store:store-announcement! store (diagnostic :request id :group 1)))
      (assert (= 2 (store:store-announcement-count store)))
      (store:store-forget-request! store id)
      (assert (zerop (store:store-announcement-count store))))
    (assert (zerop (store:store-request-count store))))
  (let ((store (store:diagnostic-store-new)))
    (store:store-add! store (diagnostic :start 0 :end 10 :severity store:DiagnosticWarning))
    (store:store-add! store (diagnostic :start 1 :end 5 :severity store:DiagnosticError :summary "wide"))
    (store:store-add! store (diagnostic :start 2 :end 3 :severity store:DiagnosticError :summary "precise"))
    (assert (= 4 (store:store-rank-for-file store "buffer://1")))
    (let ((best (coalton-impl/runtime/optional:unwrap-cl-some
                 (store:store-at-position store "buffer://1" 2))))
      (assert (equal "precise" (store:diagnostic-summary best))))
    (assert (= 2 (length (store:store-for-range store "buffer://1" 4 5)))))
  (let ((store (store:diagnostic-store-new)))
    (store:store-add-remap! store "temp-a" "buffer://1")
    (store:store-track-request! store 10)
    (store:store-add-remap! store "temp-b" "buffer://2")
    (store:store-track-request! store 11)
    (store:store-clear-pending-remaps! store)
    (assert (equal "buffer://1" (store:store-remap-file store (coalton:Some 10) "temp-a")))
    (assert (equal "buffer://2" (store:store-remap-file store (coalton:Some 11) "temp-b")))
    (assert (equal "temp-b" (store:store-remap-file store (coalton:Some 10) "temp-b")))
    (store:store-clear-all! store)
    (assert (equal '("temp-a") (store:store-request-temporary-files store 10)))
    (store:store-forget-request! store 10)
    (assert (null (store:store-request-temporary-files store 10))))
  t)
