(defpackage #:mine-tests/diagnostic-adapter
  (:use #:cl)
  (:local-nicknames (#:diagnostics #:mine/app/diagnostics)
                    (#:store #:mine/app/diagnostic-store))
  (:export #:run-diagnostic-adapter-tests #:run-diagnostic-cleanup-tests))

(in-package #:mine-tests/diagnostic-adapter)

(defun run-diagnostic-adapter-tests ()
  (let ((diagnostics::*diagnostic-store* (store:diagnostic-store-new)))
    (diagnostics:clear-diagnostics-for-file "buffer://1")
    (diagnostics:track-diagnostic-request 1)
    (let ((old (list :file "buffer://1" :start 2 :end 6 :severity :warning
                      :request 1 :group 0 :label-kind :primary :summary "old")))
      (assert (diagnostics:store-diagnostic old))
      (assert (diagnostics:diagnostic-announcement-p old))
      (assert (not (diagnostics:diagnostic-announcement-p old)))
      (diagnostics:clear-diagnostics-for-file "buffer://1")
      (diagnostics:track-diagnostic-request 2)
      (assert (diagnostics:diagnostic-stale-p old))
      (assert (not (diagnostics:store-diagnostic old)))
      (assert (not (diagnostics:diagnostic-announcement-p old)))
      (diagnostics:forget-diagnostic-request 1))
    (diagnostics:store-diagnostic
     (list :file "buffer://1" :start 2 :end 4 :severity :error
           :request 2 :group 0 :label-kind :primary :summary "new"))
    (assert (= 4 (diagnostics:diagnostic-rank-for-file "buffer://1")))
    (assert (equal '((2 4 :error)) (diagnostics:line-diagnostic-spans "buffer://1" 0 10)))
    (assert (equal "new" (diagnostics:diagnostics-message-for-position "buffer://1" 2)))
    (assert (equal '(("buffer://1" 2 4)) (diagnostics::all-diagnostic-locations)))
    (diagnostics:forget-diagnostic-request 2)
    (assert (zerop (store:store-announcement-count diagnostics::*diagnostic-store*)))
    (diagnostics:invalidate-diagnostics-for-file "buffer://1")
    (assert (zerop (diagnostics:diagnostic-rank-for-file "buffer://1")))
    ;; Invalid protocol spans are normalized before entering unsigned fields.
    (assert (diagnostics:store-diagnostic
             (list :file "buffer://2" :start -2 :end -5 :summary "point" :severity :note)))
    (assert (equal '((0 0 :note)) (diagnostics:line-diagnostic-spans "buffer://2" 0 1)))
    (diagnostics:clear-all-diagnostics))
  (let ((diagnostics::*diagnostic-store* (store:diagnostic-store-new))
        (temp-a nil) (temp-b nil))
    (unwind-protect
         (progn
           (setf temp-a (diagnostics:write-temp-for-compile "(first)" "buffer://1"))
           (assert (equal (diagnostics::normalize-document-key temp-a)
                          (diagnostics:remap-runtime-source-filepath temp-a)))
           (diagnostics:track-diagnostic-request 10)
           (setf temp-b (diagnostics:write-temp-for-compile "(second)" "buffer://2"))
           (diagnostics:track-diagnostic-request 11)
           (assert (not (equal temp-a temp-b)))
           (assert (and (probe-file temp-a) (probe-file temp-b)))
           (diagnostics:clear-compile-file-remap)
           (assert (equal "buffer://1" (diagnostics::remap-diagnostic-filepath temp-a 10)))
           (assert (equal "buffer://2" (diagnostics::remap-diagnostic-filepath temp-b 11)))
           (diagnostics:clear-all-diagnostics)
           (assert (and (probe-file temp-a) (probe-file temp-b)))
           (assert (equal "buffer://1" (diagnostics:remap-runtime-source-filepath temp-a)))
           (assert (equal "buffer://2" (diagnostics:remap-runtime-source-filepath temp-b)))
           (diagnostics:forget-diagnostic-request 10)
           (assert (not (probe-file temp-a)))
           (assert (probe-file temp-b))
           (assert (equal "buffer://1" (diagnostics:remap-runtime-source-filepath temp-a)))
           (assert (equal (diagnostics::normalize-document-key temp-a)
                          (diagnostics::remap-diagnostic-filepath temp-a 10)))
           (diagnostics:forget-diagnostic-request 11)
           (assert (not (probe-file temp-b)))
           (diagnostics:clear-all-diagnostics)
           (diagnostics:clear-compile-file-remap)
           (assert (equal "buffer://1" (diagnostics:remap-runtime-source-filepath temp-a)))
           (assert (equal "buffer://2" (diagnostics:remap-runtime-source-filepath temp-b)))
           (assert (equal "buffer://other"
                          (diagnostics:remap-runtime-source-filepath "buffer://other")))
           (diagnostics:forget-all-diagnostic-requests)
           (assert (equal (diagnostics::normalize-document-key temp-a)
                          (diagnostics:remap-runtime-source-filepath temp-a)))
           (assert (equal (diagnostics::normalize-document-key temp-b)
                          (diagnostics:remap-runtime-source-filepath temp-b))))
      (diagnostics:forget-all-diagnostic-requests)))
  t)

(defun run-diagnostic-cleanup-tests ()
  (let ((diagnostics::*diagnostic-store* (store:diagnostic-store-new))
        (temporary nil))
    (unwind-protect
         (progn
           (setf temporary (diagnostics:write-temp-for-compile "(test)" "buffer://1"))
           (with-open-file (stream (compile-file-pathname temporary)
                                   :direction :output :if-exists :supersede)
             (write-line "private output" stream))
           (diagnostics:track-diagnostic-request 20)
           (diagnostics:track-diagnostic-request 21)
           (diagnostics:store-diagnostic
            (list :file "buffer://1" :start 0 :end 1 :severity :note))
           (diagnostics:forget-all-diagnostic-requests)
           (assert (not (probe-file temporary)))
           (assert (not (probe-file (compile-file-pathname temporary))))
           (assert (zerop (store:store-request-count diagnostics::*diagnostic-store*)))
           (assert (= 1 (diagnostics:diagnostic-rank-for-file "buffer://1"))))
      (diagnostics:forget-all-diagnostic-requests)))
  t)
