(defpackage #:mine-tests/editor-layout
  (:use #:coalton #:coalton-prelude)
  (:local-nicknames
   (#:layout #:mine/app/layout)
   (#:wt #:mine/widget/types)
   (#:input #:mine/widget/input)
   (#:cell #:coalton/cell)
   (#:screen #:mine/term/screen)))

(in-package #:mine-tests/editor-layout)
(named-readtables:in-readtable coalton:coalton)

(coalton-toplevel
  (declare geometry-parts (layout:CenterGeometry -> List (List UFix)))
  (define (geometry-parts geometry)
    (map (fn (part)
           (match part
             ((None) Nil)
             ((Some rect) [(wt:.rect-x rect) (wt:.rect-y rect)
                           (wt:.rect-width rect) (wt:.rect-height rect)])))
         [(layout:.cg-editor geometry) (layout:.cg-editor-status geometry)
          (layout:.cg-repl geometry) (layout:.cg-repl-status geometry)
          (layout:.cg-repl-strip geometry)]))

  (declare viewport-data (input:InputWidget * wt:Rect -> List UFix))
  (define (viewport-data iw rect)
    (let viewport = (input:input-widget-viewport iw rect))
    [(input:.iv-scroll viewport) (input:.iv-cursor-row viewport)
     (input:.iv-cursor-col viewport) (input:.iv-line-scroll viewport)])

  (declare viewport-cursor (input:InputWidget * wt:Rect -> Optional (Tuple UFix UFix)))
  (define (viewport-cursor iw rect) (input:.iv-cursor (input:input-widget-viewport iw rect)))

  (declare screen-cursor (screen:Screen -> Tuple UFix UFix))
  (define (screen-cursor scr)
    (Tuple (cell:read (screen::.screen-cursor-col scr))
           (cell:read (screen::.screen-cursor-row scr)))))

(named-readtables:in-readtable :standard)
(in-package #:mine-tests)

(defun %layout-xy (position)
  (let ((value (app::%coalton-optional-value-or-nil position)))
    (when value (list (coalton-prelude:fst value) (coalton-prelude:snd value)))))

(defun check-editor-center-layout-table ()
  (dolist (case (list (list mine/app/state:CenterEditor '((2 1 78 21) (2 22 78 1) nil nil nil))
                     (list mine/app/state:CenterEditorFull '((2 1 78 22) nil nil nil nil))
                     (list mine/app/state:CenterEditorFullReplRow '((2 1 78 21) nil nil nil (2 22 78 1)))
                     (list mine/app/state:CenterReplFull '(nil nil (2 1 78 21) (2 22 78 1) nil))
                     (list mine/app/state:CenterEditorReplSplit '((2 1 78 13) (2 14 78 1) (2 15 78 7) (2 22 78 1) nil))))
    (%check (equal (second case)
                   (mine-tests/editor-layout::geometry-parts
                    (mine/app/layout:center-geometry (first case) (wt:Rect 2 1 78 22))))
            "Unexpected center geometry for ~S" (first case))
    (loop for height from 0 to 8 do
      (dolist (width '(0 1 20))
        (let ((parts (remove nil (mine-tests/editor-layout::geometry-parts
                                 (mine/app/layout:center-geometry (first case) (wt:Rect 2 1 width height)))))
              (covered nil))
          (dolist (part parts)
            (destructuring-bind (x y w h) part
              (%check (and (>= x 2) (>= y 1) (<= (+ x w) (+ 2 width)) (<= (+ y h) (+ 1 height)))
                      "Layout escaped its rectangle: ~S" part)
              (loop for row from y below (+ y h) do
                (%check (not (member row covered)) "Center panes overlap on row ~D" row)
                (push row covered)))))))))

(defun check-editor-input-viewport-matches-rendering ()
  (let* ((iw (mine/widget/input:input-widget-new "> " mine/term/color:default-style mine/term/color:default-style))
         (text (format nil "ignored earlier line~%~C界abc" #\Tab))
         (rect (wt:Rect 10 5 8 1))
         (scr (mine/term/screen:screen-new 40 12)))
    (mine/widget/input:input-widget-set-text! iw text)
    (%check (equal '(1 1 9 4) (mine-tests/editor-layout::viewport-data iw rect))
            "Input viewport should use current-line tab/wide columns and vertical scrolling")
    (%check (equal '(17 5) (%layout-xy (mine-tests/editor-layout::viewport-cursor iw rect)))
            "Input cursor should fit the horizontally scrolled viewport")
    (%check (equal '(14 5) (%layout-xy (mine/widget/input:input-widget-completion-anchor iw rect "abc")))
            "Completion should be anchored to the visible prefix on the current line")
    (mine/widget/input:input-widget-render iw scr rect)
    (let ((actual (mine-tests/editor-layout::screen-cursor scr)))
      (%check (equal '(17 5) (list (coalton-prelude:fst actual) (coalton-prelude:snd actual)))
              "Drawing must use the same cursor coordinates as completion"))
    (mine/widget/input:input-widget-set-text! iw "some text")
    (%check (equal '(10 5) (%layout-xy (mine-tests/editor-layout::viewport-cursor iw (wt:Rect 10 5 1 1))))
            "A narrow input should reserve a visible cursor cell")
    (%check (null (%layout-xy (mine-tests/editor-layout::viewport-cursor iw (wt:Rect 10 5 0 0))))
            "An empty rectangle must not expose an offscreen cursor")))

(defun check-editor-view-round-trip ()
  (let* ((ep (mine/pane/editor:editor-pane-new))
         (gb (gap:gap-from-string (format nil "abcdef~%second~%third")))
         (cs (cursor:cursor-new)))
    (cursor:cursor-move-to-buffer-position! gb cs 2)
    (cursor:cursor-start-selection! cs)
    (cursor:cursor-move-to-buffer-position! gb cs 5)
    (mine/pane/editor:editor-pane-set-scroll-row! ep 1)
    (let ((saved (mine/pane/editor:editor-pane-save-view ep cs)))
      (cursor:cursor-move-to-buffer-position! gb cs 0)
      (cursor:cursor-clear-selection! cs)
      (mine/pane/editor:editor-pane-set-scroll-row! ep 0)
      (mine/pane/editor:editor-pane-restore-view! ep gb cs saved)
      (%check (and (= 5 (cursor:cursor-position cs))
                   (= 2 (app::%coalton-optional-value-or-nil (cursor:cursor-selection-anchor cs)))
                   (= 1 (mine/pane/editor:editor-pane-scroll-row ep)))
              "Saved editor views should restore cursor, selection, and scrolling")
      (cursor:cursor-move-down! gb cs)
      (%check (= 12 (cursor:cursor-position cs)) "Restored views should preserve the sticky visual target")
      (gap:gap-reset! gb "x")
      (mine/pane/editor:editor-pane-restore-view! ep gb cs saved)
      (%check (and (= 1 (cursor:cursor-position cs))
                   (= 1 (app::%coalton-optional-value-or-nil (cursor:cursor-selection-anchor cs)))
                   (= 0 (mine/pane/editor:editor-pane-scroll-row ep)))
              "Restoring a view after a shorter refresh should clamp all document positions"))))

(defun run-editor-layout-tests ()
  (dolist (test '(check-editor-center-layout-table
                  check-editor-input-viewport-matches-rendering
                  check-editor-view-round-trip))
    (funcall test))
  t)
