(defpackage #:mine-tests/editor-layout
  (:use #:coalton #:coalton-prelude)
  (:local-nicknames
   (#:layout #:mine/app/layout)
   (#:wt #:mine/widget/types)
   (#:input #:mine/widget/input)
   (#:editor #:mine/pane/editor)
   (#:buf #:mine/buffer/buffer)
   (#:color #:mine/term/color)
   (#:seq #:coalton/seq)
   (#:vec #:coalton/vector)
   (#:term #:mine/term/terminal)
   (#:state #:mine/app/state)
   (#:cell #:coalton/cell)
   (#:screen #:mine/term/screen)))

(in-package #:mine-tests/editor-layout)
(named-readtables:in-readtable coalton:coalton)

(coalton-toplevel
  (declare geometry-parts (layout:CenterGeometry -> List (List UFix)))
  (define (geometry-parts geometry)
    (map (fn (part)
           (match part
             ((None) Nil)
             ((Some rect) [(wt:.rect-x rect) (wt:.rect-y rect)
                           (wt:.rect-width rect) (wt:.rect-height rect)])))
         [(layout:.cg-editor geometry) (layout:.cg-editor-status geometry)
          (layout:.cg-repl geometry) (layout:.cg-repl-status geometry)
          (layout:.cg-repl-strip geometry)]))

  (declare viewport-data (input:InputWidget * wt:Rect -> List UFix))
  (define (viewport-data iw rect)
    (let viewport = (input:input-widget-viewport iw rect))
    [(input:.iv-scroll viewport) (input:.iv-cursor-row viewport)
     (input:.iv-cursor-col viewport) (input:.iv-line-scroll viewport)])

  (declare viewport-cursor (input:InputWidget * wt:Rect -> Optional (Tuple UFix UFix)))
  (define (viewport-cursor iw rect) (input:.iv-cursor (input:input-widget-viewport iw rect)))

  (declare screen-cursor (screen:Screen -> Tuple UFix UFix))
  (define (screen-cursor scr)
    (Tuple (cell:read (screen::.screen-cursor-col scr))
           (cell:read (screen::.screen-cursor-row scr))))

  (declare screen-cell-background (screen:Screen * UFix * UFix -> color:Color))
  (define (screen-cell-background scr x y)
    (let index = (+ (* y (cell:read (screen:.screen-width scr))) x))
    (color:.style-bg (screen::.screen-cell-style
                     (vec:index-unsafe index (cell:read (screen::.screen-back scr))))))

  (declare screen-cell-foreground (screen:Screen * UFix * UFix -> color:Color))
  (define (screen-cell-foreground scr x y)
    (let index = (+ (* y (cell:read (screen:.screen-width scr))) x))
    (color:.style-fg (screen::.screen-cell-style
                     (vec:index-unsafe index (cell:read (screen::.screen-back scr))))))

  (declare fake-terminal (UFix * UFix -> term:Terminal))
  (define (fake-terminal cols rows)
    (term:Terminal (screen:screen-new cols rows) (cell:new False)
                    (term::%terminal-input-runtime-new) (cell:new (vec:new))
                    (cell:new cols) (cell:new rows)))

  (declare set-center! (state:MineState * state:CenterLayout -> Void))
  (define (set-center! st center)
    (cell:write! (state:.ms-layout st) (state:MineLayout state:TreeHidden center))
    (values))

  (declare screen-cell-character (screen:Screen * UFix * UFix -> Char))
  (define (screen-cell-character scr x y)
    (let index = (+ (* y (cell:read (screen:.screen-width scr))) x))
    (screen::.screen-cell-ch (vec:index-unsafe index (cell:read (screen::.screen-back scr)))))

  (declare captured-search-context (List editor:RenderSpan -> editor:EditorRenderContext))
  (define (captured-search-context spans)
    (editor:search-state-set! (seq:push (seq:new) 0) 1)
    (editor:search-current-set! 0)
    (let context = (editor:editor-render-context buf:ModePlainText spans (Some (Tuple 2 3))))
    (editor:search-state-clear!)
    context))

(named-readtables:in-readtable :standard)
(in-package #:mine-tests)

(defun %layout-xy (position)
  (let ((value (app::%coalton-optional-value-or-nil position)))
    (when value (list (coalton-prelude:fst value) (coalton-prelude:snd value)))))

(defun check-editor-center-layout-table ()
  (dolist (case (list (list mine/app/state:CenterEditor '((2 1 78 21) (2 22 78 1) nil nil nil))
                     (list mine/app/state:CenterEditorFull '((2 1 78 22) nil nil nil nil))
                     (list mine/app/state:CenterEditorFullReplRow '((2 1 78 21) nil nil nil (2 22 78 1)))
                     (list mine/app/state:CenterReplFull '(nil nil (2 1 78 21) (2 22 78 1) nil))
                     (list mine/app/state:CenterEditorReplSplit '((2 1 78 13) (2 14 78 1) (2 15 78 7) (2 22 78 1) nil))))
    (%check (equal (second case)
                   (mine-tests/editor-layout::geometry-parts
                    (mine/app/layout:center-geometry (first case) (wt:Rect 2 1 78 22))))
            "Unexpected center geometry for ~S" (first case))
    (loop for height from 0 to 8 do
      (dolist (width '(0 1 20))
        (let ((parts (remove nil (mine-tests/editor-layout::geometry-parts
                                 (mine/app/layout:center-geometry (first case) (wt:Rect 2 1 width height)))))
              (covered nil))
          (dolist (part parts)
            (destructuring-bind (x y w h) part
              (%check (and (>= x 2) (>= y 1) (<= (+ x w) (+ 2 width)) (<= (+ y h) (+ 1 height)))
                      "Layout escaped its rectangle: ~S" part)
              (loop for row from y below (+ y h) do
                (%check (not (member row covered)) "Center panes overlap on row ~D" row)
                (push row covered)))))))))

(defun check-editor-input-viewport-matches-rendering ()
  (let* ((iw (mine/widget/input:input-widget-new "> " mine/term/color:default-style mine/term/color:default-style))
         (text (format nil "ignored earlier line~%~C界abc" #\Tab))
         (rect (wt:Rect 10 5 8 1))
         (scr (mine/term/screen:screen-new 40 12)))
    (mine/widget/input:input-widget-set-text! iw text)
    (%check (equal '(1 1 9 4) (mine-tests/editor-layout::viewport-data iw rect))
            "Input viewport should use current-line tab/wide columns and vertical scrolling")
    (%check (equal '(17 5) (%layout-xy (mine-tests/editor-layout::viewport-cursor iw rect)))
            "Input cursor should fit the horizontally scrolled viewport")
    (%check (equal '(14 5) (%layout-xy (mine/widget/input:input-widget-completion-anchor iw rect "abc")))
            "Completion should be anchored to the visible prefix on the current line")
    (mine/widget/input:input-widget-render iw scr rect)
    (let ((actual (mine-tests/editor-layout::screen-cursor scr)))
      (%check (equal '(17 5) (list (coalton-prelude:fst actual) (coalton-prelude:snd actual)))
              "Drawing must use the same cursor coordinates as completion"))
    (mine/widget/input:input-widget-set-text! iw "some text")
    (%check (equal '(10 5) (%layout-xy (mine-tests/editor-layout::viewport-cursor iw (wt:Rect 10 5 1 1))))
            "A narrow input should reserve a visible cursor cell")
    (%check (null (%layout-xy (mine-tests/editor-layout::viewport-cursor iw (wt:Rect 10 5 0 0))))
            "An empty rectangle must not expose an offscreen cursor")))

(defun check-editor-view-round-trip ()
  (let* ((ep (mine/pane/editor:editor-pane-new))
         (gb (gap:gap-from-string (format nil "abcdef~%second~%third")))
         (cs (cursor:cursor-new)))
    (cursor:cursor-move-to-buffer-position! gb cs 2)
    (cursor:cursor-start-selection! cs)
    (cursor:cursor-move-to-buffer-position! gb cs 5)
    (mine/pane/editor:editor-pane-set-scroll-row! ep 1)
    (let ((saved (mine/pane/editor:editor-pane-save-view ep cs)))
      (cursor:cursor-move-to-buffer-position! gb cs 0)
      (cursor:cursor-clear-selection! cs)
      (mine/pane/editor:editor-pane-set-scroll-row! ep 0)
      (mine/pane/editor:editor-pane-restore-view! ep gb cs saved)
      (%check (and (= 5 (cursor:cursor-position cs))
                   (= 2 (app::%coalton-optional-value-or-nil (cursor:cursor-selection-anchor cs)))
                   (= 1 (mine/pane/editor:editor-pane-scroll-row ep)))
              "Saved editor views should restore cursor, selection, and scrolling")
      (cursor:cursor-move-down! gb cs)
      (%check (= 12 (cursor:cursor-position cs)) "Restored views should preserve the sticky visual target")
      (gap:gap-reset! gb "x")
      (mine/pane/editor:editor-pane-restore-view! ep gb cs saved)
      (%check (and (= 1 (cursor:cursor-position cs))
                   (= 1 (app::%coalton-optional-value-or-nil (cursor:cursor-selection-anchor cs)))
                   (= 0 (mine/pane/editor:editor-pane-scroll-row ep)))
              "Restoring a view after a shorter refresh should clamp all document positions"))))

(defun run-editor-layout-tests ()
  (dolist (test '(check-editor-center-layout-table
                  check-editor-input-viewport-matches-rendering
                  check-editor-view-round-trip))
    (funcall test))
  t)

(defun check-editor-render-context-isolation ()
  (let* ((ep (mine/pane/editor:editor-pane-new))
         (gb (gap:gap-from-string "abc"))
         (cs (cursor:cursor-new))
         (rect (wt:Rect 1 1 18 2))
         (scr (mine/term/screen:screen-new 24 5))
         (text-x (+ 1 (mine/pane/editor:editor-pane-gutter-width ep gb)))
         (spans (mine/pane/editor:render-spans-from-triples '((1 2 :error) (3 3 :warning))))
         (context (mine-tests/editor-layout::captured-search-context spans)))
    (mine/pane/editor:editor-pane-render-with-context ep scr rect gb cs context)
    (loop for offset from 0
          for color in (list mine/term/color:search-current-bg mine/term/color:dark-red
                             mine/term/color:slate mine/term/color:brown)
          do (%check (equalp color (mine-tests/editor-layout::screen-cell-background scr (+ text-x offset) 1))
                     "Render context should apply its captured style at offset ~D" offset))
    (mine/pane/editor:editor-pane-render-with-context
     ep scr rect gb cs (mine/pane/editor:editor-render-context buf:ModePlainText nil coalton:None))
    (loop for offset from 0 to 3
          do (%check (equalp mine/term/color:current-line-bg
                              (mine-tests/editor-layout::screen-cell-background scr (+ text-x offset) 1))
                     "A fresh render context should not inherit previous highlights at offset ~D" offset))
    (mine/term/screen:screen-clear scr)
    (mine/term/screen:screen-set-cell scr 1 3 #\X mine/term/color:default-style)
    (mine/pane/editor:editor-pane-render-with-context
     ep scr (wt:Rect 1 1 2 1) gb cs context)
    (%check (char= #\X (mine-tests/editor-layout::screen-cell-character scr 3 1))
            "A pane narrower than its gutter must not paint into a neighboring pane")))

(defun check-editor-navigation-preserves-document-views ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (manager (mine/app/state:get-bufmgr state))
           (cursor (mine/app/state:get-cursor-state state))
           (first (%editor-result-ok
                   (mine/buffer/manager:bufmgr-open-file! manager (namestring (merge-pathnames "first.lisp" directory)))))
           (second (%editor-result-ok
                    (mine/buffer/manager:bufmgr-open-file! manager (namestring (merge-pathnames "second.lisp" directory))))))
      (gap:gap-reset! (buf:buffer-gap first) "first buffer")
      (gap:gap-reset! (buf:buffer-gap second) (format nil "a~C~Cb" #\Return #\Newline))
      (mine/app/state:activate-buffer! state first)
      (cursor:cursor-move-to-buffer-position! (buf:buffer-gap first) cursor 6)
      (%check (mine/app/navigation:jump-to-document-key state (buf:buffer-document-key second) 2)
              "Navigation should find an existing buffer")
      (%check (= 3 (cursor:cursor-position cursor)) "Navigation should clamp offsets to CRLF units")
      (mine/app/state:activate-buffer! state first)
      (%check (= 6 (cursor:cursor-position cursor))
              "Navigation activation should preserve the view of the departed document"))))

(defun run-editor-render-context-tests ()
  (check-editor-render-context-isolation)
  (check-editor-navigation-preserves-document-views)
  t)

(defun check-editor-render-multiline-source-snapshot ()
  (let* ((ep (mine/pane/editor:editor-pane-new))
         (gb (gap:gap-from-string (format nil "\"first~%second\"")))
         (cs (cursor:cursor-new))
         (scr (mine/term/screen:screen-new 20 3))
         (rect (wt:Rect 0 0 20 1))
         (context (mine/pane/editor:editor-render-context buf:ModeLisp nil coalton:None)))
    (cursor:cursor-move-to-buffer-position! gb cs 8)
    (mine/pane/editor:editor-pane-set-scroll-row! ep 1)
    (mine/pane/editor:editor-pane-render-with-context ep scr rect gb cs context)
    (%check (equalp mine/term/color:plum
                    (mine-tests/editor-layout::screen-cell-foreground
                     scr (mine/pane/editor:editor-pane-gutter-width ep gb) 0))
            "Scrolled multiline strings should retain source-level syntax classification")))

(defun check-repl-output-selection-uses-visual-columns ()
  (let* ((tw (mine/widget/text:text-widget-new mine/term/color:default-style))
         (text (format nil "A界e~CZ" (code-char #x301)))
         (scr (mine/term/screen:screen-new 12 2))
         (rect (wt:Rect 2 0 5 1)))
    (mine/widget/text:text-widget-append! tw text)
    (mine/widget/text:text-widget-start-selection-at-column! tw 0 1)
    (mine/widget/text:text-widget-extend-selection-at-column! tw 0 4)
    (%check (string= (subseq text 1 4) (mine/widget/text:text-widget-selected-text tw))
            "Output selection should copy whole wide characters and their combining suffixes")
    (mine/term/screen:screen-set-cell scr 0 7 #\X mine/term/color:default-style)
    (mine/widget/text:text-widget-render tw scr rect)
    (%check (equalp mine/term/color:highlight-bg
                    (mine-tests/editor-layout::screen-cell-background scr 3 0))
            "Output highlight should begin at the visual column")
    (%check (equalp mine/term/color:highlight-bg
                    (mine-tests/editor-layout::screen-cell-background scr 5 0))
            "Output highlight should include the final selected display cell")
    (%check (char= #\X (mine-tests/editor-layout::screen-cell-character scr 7 0))
            "Output highlight must remain clipped to its pane")))

(defun check-repl-pointer-targets-match-multiline-geometry ()
  (let* ((state (%test-state))
         (term (mine-tests/editor-layout::fake-terminal 80 14))
         (repl (mine/app/state:get-repl-pane state)))
    (mine-tests/editor-layout::set-center! state mine/app/state:CenterReplFull)
    (repl:repl-pane-paste-to-input! repl (format nil "one~%two~%three~%four~%five"))
    (dotimes (i 20) (repl:repl-pane-append-output! repl (format nil "output ~D" i)))
    (repl:repl-pane-set-output-scroll! repl 0)
    (app::handle-mouse-click state term 3 7)
    (%check (eq coalton:False (repl:repl-pane-has-selection? repl))
            "The first row of multiline input must not start an output selection")
    (app::handle-mouse-click state term 3 6)
    (%check (eq coalton:True (repl:repl-pane-has-selection? repl))
            "The last output row should remain selectable")
    (%check (eq coalton:False (app::scrollbar-drag! state term 79 7))
            "The input area must not act as an output scrollbar")
    (%check (eq coalton:True (app::scrollbar-drag! state term 79 6))
            "The last drawn output row should belong to its scrollbar")
    (let ((scroll (repl:repl-pane-output-scroll repl)))
      (%check (= (- (repl:repl-pane-output-line-count repl) 6) scroll)
              "Scrollbar mapping should use the actual multiline output height")
      (app::handle-scroll-wheel! state term 3 7 -3)
      (%check (= scroll (repl:repl-pane-output-scroll repl))
              "Wheel events over input must not scroll output")
      (app::handle-scroll-wheel! state term 3 6 -3)
      (%check (= (max 0 (- scroll 3)) (repl:repl-pane-output-scroll repl))
              "Wheel events over output should scroll it"))))

(defun run-editor-geometry-integration-tests ()
  (check-editor-render-multiline-source-snapshot)
  (check-repl-output-selection-uses-visual-columns)
  (check-repl-pointer-targets-match-multiline-geometry)
  t)
