(defpackage #:mine-tests/lexer-context
  (:use #:cl)
  (:local-nicknames (#:source #:mine/syntax/context)
                    (#:lexer #:mine/syntax/lexer)
                    (#:tok #:mine/syntax/token))
  (:export #:run-lexer-context-tests))

(in-package #:mine-tests/lexer-context)

(defun colored-spans (text)
  (mapcar (lambda (token)
            (list (tok:token-kind token)
                  (subseq text (tok:token-start token) (tok:token-end token))))
          (lexer:lex-source (source:scan-source text) 0)))

(defun run-lexer-context-tests ()
  (assert (equal (list (list tok:TokOpenParen "(")
                      (list tok:TokSymbol "|x) [ y|")
                      (list tok:TokWhitespace " ")
                      (list tok:TokChar "#\\)")
                      (list tok:TokSymbol "foo")
                      (list tok:TokCloseParen ")"))
                 (colored-spans "(|x) [ y| #\\)foo)")))
  (assert (equal (list (list tok:TokCoaltonKeyword "ƒ")
                      (list tok:TokSymbol "x.x"))
                 (colored-spans "ƒx.x")))
  (let* ((text (format nil "(list \"first~% second\" |third~% fourth|)"))
         (tokens (lexer:lex-source (source:scan-source text) 0))
         (start (1+ (position #\Newline text)))
         (end (position #\Newline text :start start))
         (line (lexer:tokens-for-line tokens start end)))
    (assert (= 3 (length line)))
    (assert (eq tok:TokString (tok:token-kind (first line))))
    (assert (zerop (tok:token-start (first line))))
    (assert (= 8 (tok:token-end (first line))))
    (assert (eq tok:TokSymbol (tok:token-kind (third line))))
    (assert (= (- end start) (tok:token-end (third line)))))
  (dolist (entry mine-tests/source-context:*source-corpus*)
    (let* ((text (second entry))
           (tokens (lexer:lex-source (source:scan-source text) 0))
           (next 0))
      (dolist (token tokens)
        (assert (= next (tok:token-start token)))
        (assert (< (tok:token-start token) (tok:token-end token)))
        (assert (<= (tok:token-end token) (length text)))
        (setf next (tok:token-end token)))
      (assert (= next (length text)))))
  t)
