(defpackage #:mine-tests/paredit-context
  (:use #:cl)
  (:local-nicknames (#:source #:mine/syntax/context)
                    (#:paredit #:mine/syntax/paredit)
                    (#:gap #:mine/buffer/gap)
                    (#:buf #:mine/buffer/buffer)
                    (#:cursor #:mine/edit/cursor))
  (:export #:run-paredit-context-tests))

(in-package #:mine-tests/paredit-context)

(defun edited (text pos operation)
  (let* ((buffer (buf:buffer-new-file (buf:BufferId 901) "source-context.ct"))
         (gb (buf:buffer-gap buffer))
         (cs (cursor:cursor-new)))
    (gap:gap-insert-string! gb 0 text)
    (cursor:cursor-move-to-position! cs pos)
    (funcall operation buffer cs)
    (values (gap:gap-to-string gb) (cursor:cursor-position cs))))

(defun inserted (text pos string)
  (concatenate 'string (subseq text 0 pos) string (subseq text pos)))

(defun check-delimiters-around-literal-tokens ()
  ;; Each case has a position just before a comment, character, or escaped
  ;; symbol, a position inside it, and where close paren leaves the cursor.
  (dolist (case (list (list (format nil "(a)~%; x") 4 5 4)
                      (list (format nil "(f ; x~%)") 3 4 8)
                      (list "(f #|c|# x)" 3 5 11)
                      (list "(f #\\a)" 3 5 7)
                      (list "(f #\\(#\\))" 6 8 10)
                      (list "(f |x|)" 3 4 7)))
    (destructuring-bind (text before inside close) case
      (flet ((check-edit (operation pos expected-text expected-cursor)
               (multiple-value-bind (actual-text actual-cursor) (edited text pos operation)
                 (assert (and (equal expected-text actual-text)
                              (eql expected-cursor actual-cursor))
                         ()
                         "~A at ~D in ~S gave ~S with cursor ~D"
                         operation pos text actual-text actual-cursor))))
        (check-edit #'paredit:paredit-open-paren! before (inserted text before "()") (1+ before))
        (check-edit #'paredit:paredit-open-bracket! before (inserted text before "[]") (1+ before))
        (check-edit #'paredit:paredit-doublequote! before (inserted text before "\"\"") (1+ before))
        (check-edit #'paredit:paredit-close-paren! before text close)
        (check-edit #'paredit:paredit-open-paren! inside (inserted text inside "(") (1+ inside))
        (check-edit #'paredit:paredit-open-bracket! inside (inserted text inside "[") (1+ inside))
        (check-edit #'paredit:paredit-doublequote! inside (inserted text inside "\"") (1+ inside))
        (check-edit #'paredit:paredit-close-paren! inside (inserted text inside ")") (1+ inside))))))

(defun run-paredit-context-tests ()
  (dolist (text '("'(a b)" "#'(lambda (x) x)" "ƒx.(+ x 1)" "|a b)|" "#\\)"))
    (let ((gb (gap:gap-from-string text)))
      (assert (eql (length text) (paredit::scan-forward-sexp gb 0)))
      (assert (eql 0 (paredit::scan-backward-sexp gb (length text))))))
  (let* ((text "(f |)| [#\\] 2])")
         (gb (gap:gap-from-string text)))
    (assert (eql (1- (length text)) (paredit:find-matching-close gb 0)))
    (assert (eql 0 (paredit:scan-matching-open-paren gb (1- (length text)))))
    (assert (eq coalton:None (paredit:scan-matching-open-paren gb 4))))
  (assert (eq coalton:None (paredit:find-matching-close (gap:gap-from-string "([)]") 0)))
  (assert (equal "|a(b|" (edited "|ab|" 2 #'paredit:paredit-open-paren!)))
  (assert (equal "#|a(b|#" (edited "#|ab|#" 3 #'paredit:paredit-open-paren!)))
  (assert (equal "\"a(" (edited "\"a" 2 #'paredit:paredit-open-paren!)))
  (assert (equal ";a(" (edited ";a" 2 #'paredit:paredit-open-paren!)))
  (assert (equal "|ab|" (edited "|a)b|" 2 #'paredit:paredit-delete!)))
  (assert (equal "|ab|" (edited "|a)b|" 3 #'paredit:paredit-backspace!)))
  (check-delimiters-around-literal-tokens)
  t)
