(defpackage #:mine-tests/paredit-context
  (:use #:cl)
  (:local-nicknames (#:source #:mine/syntax/context)
                    (#:paredit #:mine/syntax/paredit)
                    (#:gap #:mine/buffer/gap)
                    (#:buf #:mine/buffer/buffer)
                    (#:cursor #:mine/edit/cursor))
  (:export #:run-paredit-context-tests))

(in-package #:mine-tests/paredit-context)

(defun edited (text pos operation)
  (let* ((buffer (buf:buffer-new-file (buf:BufferId 901) "source-context.ct"))
         (gb (buf:buffer-gap buffer))
         (cs (cursor:cursor-new)))
    (gap:gap-insert-string! gb 0 text)
    (cursor:cursor-move-to-position! cs pos)
    (funcall operation buffer cs)
    (gap:gap-to-string gb)))

(defun run-paredit-context-tests ()
  (dolist (text '("'(a b)" "#'(lambda (x) x)" "ƒx.(+ x 1)" "|a b)|" "#\\)"))
    (let ((gb (gap:gap-from-string text)))
      (assert (eql (length text) (paredit::scan-forward-sexp gb 0)))
      (assert (eql 0 (paredit::scan-backward-sexp gb (length text))))))
  (let* ((text "(f |)| [#\\] 2])")
         (gb (gap:gap-from-string text)))
    (assert (eql (1- (length text)) (paredit:find-matching-close gb 0)))
    (assert (eql 0 (paredit:scan-matching-open-paren gb (1- (length text)))))
    (assert (eq coalton:None (paredit:scan-matching-open-paren gb 4))))
  (assert (eq coalton:None (paredit:find-matching-close (gap:gap-from-string "([)]") 0)))
  (assert (equal "|a(b|" (edited "|ab|" 2 #'paredit:paredit-open-paren!)))
  (assert (equal "#|a(b|#" (edited "#|ab|#" 3 #'paredit:paredit-open-paren!)))
  (assert (equal "\"a(" (edited "\"a" 2 #'paredit:paredit-open-paren!)))
  (assert (equal ";a(" (edited ";a" 2 #'paredit:paredit-open-paren!)))
  (assert (equal "|ab|" (edited "|a)b|" 2 #'paredit:paredit-delete!)))
  (assert (equal "|ab|" (edited "|a)b|" 3 #'paredit:paredit-backspace!)))
  t)
