(defpackage #:mine-tests/source-context
  (:use #:cl)
  (:local-nicknames (#:source #:mine/syntax/context))
  (:export #:run-source-context-tests #:*source-corpus* #:*completion-cases*))

(in-package #:mine-tests/source-context)

(defun check (condition format-control &rest args)
  (unless condition (error (apply #'format nil format-control args))))

(defun optional-value (value)
  (unless (coalton-impl/runtime/optional:cl-none-p value)
    (coalton-impl/runtime/optional:unwrap-cl-some value)))

(defparameter *source-corpus*
  (list
   (list "empty" "" source:SourceComplete)
   (list "line comment" "; ( [ \"" source:SourceComplete)
   (list "nested block comments" "#| ( #| ] \" |# ) |#" source:SourceComplete)
   (list "literal parentheses" "(list #\\) #\\( #\\; #\\Space \"(])\")" source:SourceComplete)
   (list "escaped symbols" "(f a\\)b |x(y]|)" source:SourceComplete)
   (list "brackets and vectors" "(f [1 2] #(3 4))" source:SourceComplete)
   (list "reader prefixes" "'(a) `(,b ,@c) #'(lambda (x) x) #.(f) #2A((1)) #+sbcl (f)" source:SourceComplete)
   (list "character followed by symbol" "(list #\\)foo)" source:SourceComplete)
   (list "unfinished string" "(f \"a" source:SourceIncomplete)
   (list "unfinished escape" "(f \"a\\" source:SourceIncomplete)
   (list "unfinished block comment" "#| a #| b |#" source:SourceIncomplete)
   (list "unfinished escaped symbol" "|a(b" source:SourceIncomplete)
   (list "unfinished symbol escape" "foo\\" source:SourceIncomplete)
   (list "unfinished character" "#\\" source:SourceIncomplete)
   (list "unfinished dispatch" "#" source:SourceIncomplete)
   (list "unfinished quote" "'" source:SourceIncomplete)
   (list "unfinished feature body" "#+sbcl" source:SourceIncomplete)
   (list "unfinished feature expression" "#+(and sbcl" source:SourceIncomplete)
   (list "unfinished outer list" "((f)" source:SourceIncomplete)
   (list "unfinished bracket" "[1 2" source:SourceIncomplete)
   (list "unexpected close" ")" source:SourceMalformed)
   (list "wrong close" "(]" source:SourceMalformed)
   (list "crossed delimiters" "([)]" source:SourceMalformed)))

(defun check-corpus ()
  (dolist (entry *source-corpus*)
    (destructuring-bind (label text expected) entry
      (let* ((context (source:scan-source text))
             (actual (source:source-completeness context)))
        (check (eq expected actual) "~A: expected ~S, got ~S for ~S" label expected actual text)
        (check (eq (source:source-input-ready? context)
                   (if (eq expected source:SourceIncomplete) coalton:False coalton:True))
               "~A: unexpected REPL readiness" label)))))

(defun check-literal-classes ()
  (dolist (entry (list (list "\"abc" 4 source:SourceString)
                      (list "\"abc\"" 5 source:SourceCode)
                      (list "#|abc" 5 source:SourceBlockComment)
                      (list "#|abc|#" 7 source:SourceCode)
                      (list "#\\)" 2 source:SourceCharacter)
                      (list "foo\\)bar" 4 source:SourceEscapedSymbol)
                      (list "|a(b|" 2 source:SourceEscapedSymbol)
                      (list "; comment" 9 source:SourceLineComment)
                      (list (format nil "; (~%x") 3 source:SourceCode)))
    (destructuring-bind (text pos expected) entry
      (check (eq expected (source:source-class-at (source:scan-source text) pos))
             "Wrong lexical class at ~D in ~S" pos text))))

(defun check-package-context ()
  (let* ((text (format nil "(in-package #:first)~%; (in-package #:comment)~%~S~%'(in-package #:quoted)~%(defun f () (in-package #:nested))~%(cl:in-package ~S)~%x"
                       "(in-package #:string)" "Second"))
         (context (source:scan-source text))
         (second (search "(cl:in-package" text)))
    (check (null (optional-value (source:source-package-before context 0)))
           "Package context before the first form should be empty")
    (check (equal "FIRST" (optional-value (source:source-package-before context second)))
           "Comments, strings, quotations, and nested forms must not change package context")
    (check (equal "Second" (optional-value (source:source-package-before context (length text))))
           "Expected nearest actual IN-PACKAGE, preserving string case"))
  (dolist (text '("(|in-package| #:wrong)" "(|CL:IN-PACKAGE| #:wrong)" "(cl\\:in-package #:wrong)" "#.(in-package #:wrong)"))
    (check (null (optional-value (source:source-package-before (source:scan-source text) (length text))))
           "Escaped, quoted, and reader-evaluated heads must not be package setters: ~S" text))
  (let ((text "(in-package #:|Mixed:Case|)"))
    (check (equal "Mixed:Case" (optional-value (source:source-package-before (source:scan-source text) (length text))))
           "Expected escaped package name case and colon to be preserved")))

(defun range-text (context range)
  (let ((pair (optional-value range)))
    (when pair
      (subseq (source:source-text context)
              (coalton-prelude:fst pair) (coalton-prelude:snd pair)))))

(defun check-form-spans ()
  (let* ((text (format nil "; bogus ( ]~%(progn (f ~S)~% '(a [1 2])~% (g #\\)))" ")"))
         (context (source:scan-source text))
         (f-pos (search "(f " text))
         (quoted-pos (search "(a [" text)))
    (check (equal "(f \")\")" (range-text context (source:source-compile-form-range context (+ f-pos 2))))
           "Compile spans must ignore delimiters inside comments and strings")
    (check (equal "'(a [1 2])" (range-text context (source:source-smallest-list-range context (+ quoted-pos 2))))
           "Smallest list span must retain its quote prefix")
    (check (equal "'(a [1 2])" (range-text context (source:source-smallest-list-range context (1- quoted-pos))))
           "Point on a reader prefix must select the prefixed list")
    (check (equal "[1 2]" (range-text context (source:source-smallest-list-range context (+ quoted-pos 5))))
           "Nested bracket span should not absorb outer reader prefix")
    (check (equal "f" (optional-value (source:source-enclosing-head context (+ f-pos 5))))
           "Hint head should ignore a close delimiter inside a string"))
  (let* ((context (source:scan-source "(outer (inner))"))
         (after-inner 14))
    (check (equal "outer" (optional-value (source:source-enclosing-head context after-inner)))
           "After a closing delimiter, the containing outer call supplies the hint")
    (check (equal "(outer (inner))" (range-text context (source:source-smallest-list-range context after-inner)))
           "After a closing delimiter, select the enclosing list rather than the previous list")
    (check (null (optional-value (source:source-enclosing-head context 15)))
           "After a complete top-level form, there is no enclosing hint"))
  (check (null (optional-value (source:source-smallest-list-range (source:scan-source "(unfinished") 4)))
         "An incomplete list is not an evaluable enclosing form"))

(defun check-no-reader-evaluation ()
  (let ((marker 0))
    ;; The source contains a reader expression, but scanning never READs it.
    (declare (special marker))
    (source:scan-source "#.(progn (incf marker) '(in-package #:wrong))")
    (check (zerop marker) "Source scanning must not execute reader expressions")))

(defparameter *completion-cases*
  (list (list "(foo bar)" 8 "bar")
        (list "(foo bar)" 7 "ba")
        (list "(foo bar)" 0 "")
        (list "; hidden" 8 "")
        (list "\"hidden\"" 4 "")
        (list "#\\Space" 7 "")
        (list "#|hidden|# (foo)" 5 "")
        (list "(|two words|)" 12 "|two words|")
        (list "(p:|with space|)" 15 "p:|with space|")
        (list "(foo a\\ b)" 9 "a\\ b")
        (list "|unfinished name" 16 "|unfinished name")
        (list "foo" 99 "foo")))

(defun check-source-symbols ()
  (dolist (entry *completion-cases*)
    (destructuring-bind (text pos expected) entry
      (check (equal expected (source:source-symbol-prefix (source:scan-source text) pos))
             "Unexpected source prefix at ~D in ~S" pos text)))
  (let ((context (source:scan-source "(foo bar)")))
    (check (equal "bar" (optional-value (source:source-symbol-at context 8)))
           "Symbol lookup at a closing delimiter should use the preceding symbol")
    (check (equal "foo" (optional-value (source:source-symbol-at context 1)))
           "Symbol lookup at its start should include the whole symbol"))
  (let* ((parts (source:source-symbol-parts "pkg:|Case:Sensitive|"))
         (package (optional-value (coalton-prelude:fst parts))))
    (check (and (equal "PKG" package)
                (equal "Case:Sensitive" (coalton-prelude:snd parts)))
           "Symbol decoding must preserve escaped case and colons"))
  (check (equal "f" (optional-value (source:source-first-head (source:scan-source (format nil "; ignored~%(f x)")))))
         "First-form head detection must ignore leading comments"))

(defun run-source-context-tests ()
  (check-corpus)
  (check-literal-classes)
  (check-package-context)
  (check-form-spans)
  (check-no-reader-evaluation)
  (check-source-symbols)
  t)
