(in-package #:mine-tests)

(defun check-buffer-switch-restores-document-view ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (first (namestring (merge-pathnames "first.lisp" directory)))
           (second (namestring (merge-pathnames "second.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state))
           (ep (mine/app/state:get-editor-pane state)))
      (%write-utf8-file first (format nil "first~%second~%third~%fourth~%"))
      (%write-utf8-file second "other")
      (app::open-loose-file! state first)
      (cursor:cursor-move-to-position! cs 8)
      (cursor:cursor-start-selection! cs)
      (cursor:cursor-move-to-position! cs 12)
      (mine/pane/editor:editor-pane-set-scroll-row! ep 1)
      (app::open-loose-file! state second)
      (%check (= 0 (cursor:cursor-position cs)) "New document inherited the previous cursor")
      (%check (coalton-impl/runtime/optional:cl-none-p (cursor:cursor-selection-anchor cs))
              "New document inherited a selection")
      (app::open-loose-file! state first)
      (%check (= 12 (cursor:cursor-position cs)) "Returning to a document lost its cursor")
      (%check (= 8 (coalton-impl/runtime/optional:unwrap-cl-some
                    (cursor:cursor-selection-anchor cs)))
              "Returning to a document lost its selection")
      (%check (= 1 (mine/pane/editor:editor-pane-scroll-row ep))
              "Returning to a document lost its viewport"))))

(defun check-refresh-failure-preserves-edits-and-history ()
  (with-test-directory (directory)
    (let* ((state (%test-state))
           (path (namestring (merge-pathnames "refresh.lisp" directory)))
           (cs (mine/app/state:get-cursor-state state)))
      (%write-utf8-file path "original")
      (app::open-loose-file! state path)
      (let ((buffer (%test-current-buffer state)))
        (ops:insert-string! buffer (buf:buffer-undo buffer) cs "unsaved ")
        (with-open-file (stream path :direction :output :if-exists :supersede
                                    :element-type '(unsigned-byte 8))
          (write-byte #xff stream))
        (app::%do-refresh-file! state path)
        (%check (eq buffer (%test-current-buffer state)) "Failed refresh replaced the document")
        (%check (string= "unsaved original" (gap:gap-to-string (buf:buffer-gap buffer)))
                "Failed refresh destroyed unsaved text")
        (%check (buf:buffer-dirty? buffer) "Failed refresh cleared dirty state")
        (%check (ops:undo! buffer cs) "Failed refresh discarded undo history")
        (%check (string= "original" (gap:gap-to-string (buf:buffer-gap buffer)))
                "Undo after a failed refresh did not restore the document")))))

(defun check-beam-target-and-package-share-literal-aware-source ()
  (let* ((text (format nil "(in-package #:correct)~%; (in-package #:wrong)~%(defun f () \")\")"))
         (gb (gap:gap-from-string text))
         (start (search "(defun" text))
         (range (app::%find-compile-target-cl gb (+ start 14))))
    (%check (equal (cons start (length text)) range)
            "Beam target was cut at a parenthesis inside a string: ~S" range)
    (%check (string= "CORRECT" (app::%find-in-package-before gb start))
            "A comment changed the beaming package"))
  (let* ((text "'(a (b))")
         (gb (gap:gap-from-string text))
         (range (coalton-impl/runtime/optional:unwrap-cl-some
                 (app::%find-quick-result-target gb 2))))
    (%check (and (= 0 (coalton-prelude:fst range))
                 (= (length text) (coalton-prelude:snd range)))
            "Quick Result stripped a quote from the selected form")))

(defun run-workflow-tests ()
  (dolist (test '(check-buffer-switch-restores-document-view
                  check-refresh-failure-preserves-edits-and-history
                  check-beam-target-and-package-share-literal-aware-source))
    (format t "~&~A~%" test)
    (funcall test))
  t)
