(coalton-cffi/utils:define-cffi-package #:coalton-cffi

  (:documentation "A Coalton package for interfacing with C foreign functions.")
  
  (:use
   #:coalton
   #:coalton-prelude)

  (:import-from
   #:coalton-cffi/aliases
   #:define-foreign-integer-alias
   #:ForeignChar
   #:UnsignedForeignChar
   #:Short
   #:UnsignedShort
   #:Int
   #:UnsignedInt
   #:Long
   #:UnsignedLong
   #:LongLong
   #:UnsignedLongLong
   #:Float
   #:Double
   #:Bool
   #:IntPtr
   #:UIntPtr
   #:Size
   #:SSize
   #:PtrDiff
   #:Offset)
  (:export
   #:define-foreign-integer-alias
   #:ForeignChar
   #:UnsignedForeignChar
   #:Short
   #:UnsignedShort
   #:Int
   #:UnsignedInt
   #:Long
   #:UnsignedLong
   #:LongLong
   #:UnsignedLongLong
   #:Float
   #:Double
   #:Bool
   #:IntPtr
   #:UIntPtr
   #:Size
   #:SSize
   #:PtrDiff
   #:Offset)

  (:import-from
   #:coalton-cffi/complex
   #:cl-complex-float
   #:cl-complex-double)
  (:export
   #:cl-complex-float
   #:cl-complex-double)

  (:import-from
   #:coalton-cffi/types
   #:ForeignType
   #:foreign-type-size
   #:foreign-struct-type?
   #:ForeignRepr
   #:foreign-repr
   #:foreign-repr-of
   #:coalton-type-to-foreign-type
   #:define-foreign-repr-instance)
  (:export
   #:ForeignType
   #:foreign-type-size
   #:foreign-struct-type?
   #:ForeignRepr
   #:foreign-repr
   #:foreign-size
   #:foreign-repr-of
   #:foreign-size-of
   #:coalton-type-to-foreign-type
   #:define-foreign-repr-instance)

  (:import-from
   #:coalton-cffi/pointers
   #:Pointer
   #:null-pointer
   #:null-pointer?
   #:foreign-alloc-raw
   #:foreign-alloc
   #:foreign-alloc-uninitialized
   #:foreign-free
   #:unsafe-reinterpret
   #:shift-pointer
   #:SimpleForeignRepr
   #:mem-ref
   #:mem-set!
   #:mem-aref
   #:mem-aset!
   #:mem-aptr
   #:mem-cpy-raw
   #:mem-cpy
   #:mem-acpy
   #:define-simple-foreign-repr-instance
   #:with-array-pointer)
  (:export
   #:Pointer
   #:foreign-alloc-raw
   #:foreign-alloc
   #:foreign-alloc-uninitialized
   #:foreign-free
   #:unsafe-reinterpret
   #:SimpleForeignRepr
   #:mem-ref
   #:mem-set!
   #:mem-aref
   #:mem-aset!
   #:mem-aptr
   #:define-simple-foreign-repr-instance)

  (:import-from
   #:coalton-cffi/boxes
   #:Box
   #:box
   #:unbox
   #:BoxedPointer
   #:box-pointer
   #:unbox-pointer)
  (:export
   #:Box
   #:box
   #:unbox
   #:BoxedPointer
   #:box-pointer
   #:unbox-pointer)

  (:import-from
   #:coalton-cffi/libraries
   #:ForeignLibrary
   #:load-foreign-library
   #:unload-foreign-library
   #:define-foreign-library)
  (:export
   #:ForeignLibrary
   #:load-foreign-library
   #:unload-foreign-library
   #:define-foreign-library)

  (:import-from
   #:coalton-cffi/structs
   #:Slot
   #:slot-offset
   #:slot-pointer
   #:slot-ref
   #:slot-set!
   #:slot-aref
   #:slot-aset!
   #:slot-aptr
   #:define-foreign-struct)
  (:export
   #:Slot
   #:slot-offset
   #:slot-pointer
   #:slot-ref
   #:slot-set!
   #:slot-aref
   #:slot-aset!
   #:slot-aptr
   #:define-foreign-struct)

  (:import-from
   #:coalton-cffi/functions
   #:define-foreign-function)
  (:export
   #:define-foreign-function)

  (:import-from
   #:coalton-cffi/enums
   #:define-foreign-enum)
  (:export
   #:define-foreign-enum))
