(cl:in-package #:coalton-native-tests)

(define-test simple-hashtable ()
  (let ((ht (make-hashtable))
        (insert! (hashtable-set! ht))
        (get (hashtable-get ht)))
    (progn
      (insert! "zero" 0)
      (insert! "one" 1)
      (insert! "two" 2)
      (insert! "three" 3)
      (is (== (Some 0) (get "zero")))
      (is (== (Some 1) (get "one")))
      (is (== (Some 2) (get "two")))
      (is (== (Some 3) (get "three")))
      (is (isNone (get "four")))
      (is (== 4 (hashtable-count ht)))
      (hashtable-remove! ht "zero")
      (is (isNone (get "zero")))
      (is (== 3 (hashtable-count ht))))))
