(in-package #:coalton-tests)

(defun codegen-test-call-count (function callee)
  (let ((count 0))
    (traverse:traverse
     (tc:lookup-code entry:*global-environment* (intern function))
     (list
      (traverse:action (:after ast:node-direct-application node)
        (when (eq (intern callee) (ast:node-direct-application-rator node))
          (incf count))
        (values))))
    count))

(deftest scalar-replacement-preserves-field-evaluation ()
  (with-codegen-test-environment
    (codegen-test-event-recorder)
    (codegen-test-compile
     "(define-struct Coords (x Integer) (y Integer) (z Integer))
      (declare measure (Integer -> Integer))
      (define (measure n)
        (let ((point (Coords (observe n) (observe 2) (observe 3))))
          (observe 4)
          (if (== n 0) 0 (+ (.x point) (.x point)))))
      (declare unused-error (Integer -> Integer))
      (define (unused-error n)
        (let ((point (Coords (observe n)
                            (lisp (-> Integer) () (cl:error \"unused field\"))
                            (observe 3))))
          (observe 4)
          (.x point)))")
    ;; Both repeated reads and an untaken branch must leave initializers eager.
    (dolist (n '(0 21))
      (setf *codegen-events* nil)
      (is (= (* 2 n) (codegen-test-eval (format nil "(measure ~D)" n))))
      (is (equal (list n 2 3 4) (reverse *codegen-events*))))
    (setf *codegen-events* nil)
    (signals simple-error (codegen-test-eval "(unused-error 1)"))
    (is (equal '(1) *codegen-events*))
    ;; Check Coalton's IR, not whether a particular Lisp backend eliminates it.
    (dolist (function '("MEASURE" "UNUSED-ERROR"))
      (is (= (if (coalton-impl/settings:coalton-release-p) 0 1)
             (codegen-test-call-count function "COORDS"))))))

(deftest scalar-replacement-through-inline-bindings ()
  (with-codegen-test-environment
    (codegen-test-event-recorder)
    (codegen-test-compile
     "(define-struct Coords (x Integer) (y Integer))
      (inline)
      (declare make-point (Integer * Integer -> Coords))
      (define (make-point x y) (Coords (observe x) (observe y)))
      (declare measure (Integer -> Integer))
      (define (measure n)
        (let point = (make-point (observe n) (observe 2)))
        (observe 3)
        (+ (.x point) (.y point)))
      (declare dependent (Integer -> Integer))
      (define (dependent n)
        (let ((sum (+ (.x point) (.y point)))
              (point (Coords (observe n) (observe 2)))
              (after (observe sum)))
          (observe 4)
          after))")
    (is (= 42 (codegen-test-eval "(measure 40)")))
    (is (equal '(40 2 40 2 3) (reverse *codegen-events*)))
    (setf *codegen-events* nil)
    (is (= 42 (codegen-test-eval "(dependent 40)")))
    (is (equal '(40 2 42 4) (reverse *codegen-events*)))
    (dolist (function '("MEASURE" "DEPENDENT"))
      (is (= (if (coalton-impl/settings:coalton-release-p) 0 1)
             (codegen-test-call-count function "COORDS"))))))

(deftest scalar-replacement-retains-escaping-records ()
  (with-codegen-test-environment
    (codegen-test-compile
     "(define-struct Coords (x Integer) (y Integer))
      (declare return-point (Integer -> Coords))
      (define (return-point n)
        (let ((point (Coords n 2))) point))
      (declare pass-point ((Coords -> Integer) * Integer -> Integer))
      (define (pass-point f n)
        (let ((point (Coords n 2))) (+ (.x point) (f point))))
      (declare keyword-point
        ((Integer &key (:point Coords) -> Integer) * Integer -> Integer))
      (define (keyword-point f n)
        (let ((point (Coords n 2))) (f 0 :point point)))
      (declare capture-point (Integer -> (Void -> Integer)))
      (define (capture-point n)
        (let ((point (Coords n 2))) (fn () (.x point))))
      (declare lisp-point (Integer -> Integer))
      (define (lisp-point n)
        (let ((point (Coords n 2)))
          (.x (lisp (-> Coords) (point) point))))
      (declare store-point (Integer -> List Coords))
      (define (store-point n)
        (let ((point (Coords n 2))) (Cons point Nil)))
      (declare get-keyword (Integer &key (:point Coords) -> Integer))
      (define (get-keyword _ &key (point (Coords 0 0))) (.x point))")
    (dolist (function '("RETURN-POINT" "PASS-POINT" "KEYWORD-POINT"
                        "CAPTURE-POINT" "LISP-POINT" "STORE-POINT"))
      (is (= 1 (codegen-test-call-count function "COORDS"))))
    (is (= 42 (codegen-test-eval "(.x (return-point 42))")))
    (is (= 42 (codegen-test-eval "(pass-point (fn (p) (.x p)) 21)")))
    (is (= 42 (codegen-test-eval "(keyword-point get-keyword 42)")))
    (is (= 42 (codegen-test-eval "((capture-point 42))")))
    (is (= 42 (codegen-test-eval "(lisp-point 42)")))
    (is (equal '(42) (codegen-test-eval "(map .x (store-point 42))")))))

(deftest scalar-replacement-preserves-recursive-records ()
  (with-codegen-test-environment
    (codegen-test-compile
     "(define-struct LinkNode (next LinkNode) (value Integer))
      (declare cyclic (Integer -> Integer))
      (define (cyclic n)
        (let ((link (LinkNode link n))) (.value (.next link))))
      (declare mutual (Integer -> Integer))
      (define (mutual n)
        (let ((left (LinkNode right n)) (right (LinkNode left 2)))
          (+ (.value (.next left)) (.value (.next right)))))")
    (is (= 42 (codegen-test-eval "(cyclic 42)")))
    (is (= 42 (codegen-test-eval "(mutual 40)")))
    (is (= 1 (codegen-test-call-count "CYCLIC" "LINKNODE")))
    (is (= 2 (codegen-test-call-count "MUTUAL" "LINKNODE")))))

(deftest scalar-replacement-preserves-field-values ()
  (with-codegen-test-environment
    (codegen-test-event-recorder)
    (codegen-test-compile
     "(define-struct (Boxed :a) (item :a) (unused Integer))
      (declare *state* Integer)
      (define *state* 1)
      (declare snapshot (Void -> Integer))
      (define (snapshot)
        (let ((box (Boxed *state* 0)))
          (dynamic-bind ((*state* 99)) (.item box))))
      (declare callback (Integer -> Integer))
      (define (callback n)
        (let ((box (Boxed (fn (x) (observe (+ x n))) (observe 1))))
          (+ ((.item box) 2) ((.item box) 3))))
      (declare results (Integer -> Integer * Integer))
      (define (results n)
        (let ((box (Boxed n (observe 1))))
          (values (.item box) (.item box))))")
    (is (= 1 (codegen-test-eval "(snapshot)")))
    (is (= 45 (codegen-test-eval "(callback 20)")))
    (is (equal '(1 22 23) (reverse *codegen-events*)))
    (setf *codegen-events* nil)
    (is (equal '(42 42) (multiple-value-list (codegen-test-eval "(results 42)"))))
    (is (equal '(1) *codegen-events*))
    (dolist (function '("SNAPSHOT" "CALLBACK" "RESULTS"))
      (is (= (if (coalton-impl/settings:coalton-release-p) 0 1)
             (codegen-test-call-count function "BOXED"))))))
