;;;; settings.lisp
;;;;
;;;; This file contains variables that can be used to control how
;;;; Coalton works.

(in-package #:coalton-impl)

(defun coalton-release-p ()
  "Determines how redefinable code generated by Coalton is.

In development mode (i.e. (not (coalton-release-p))), Coalton turns all declare-type forms into CLOS objects
to support a repl based workflow.

In release mode Coalton compiles declare-type forms into frozen structs or even more optimal layouts which may
not support redefinition.

Development mode is the default.

Enable release mode either by setting the UNIX environment variable COALTON_ENV to \"release\", or by pushing
`:release' into `*features*'. Either of these must be done before loading Coalton.
"
  (uiop:featurep :coalton-release))

(when (string-equal (uiop:getenv "COALTON_ENV") "release")
  (pushnew :coalton-release *features*))

(when (coalton-release-p)
  (format t "~&;; COALTON starting in release mode~%"))
