name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  check-image:
    runs-on: ubuntu-latest
    outputs:
      image_repo_name: ${{ steps.set-repo.outputs.image_repo_name }}
      repo_name: ${{ steps.set-repo.outputs.repo_name }}
    steps:
      - name: Check if primary image exists
        id: set-repo
        run: |
          PRIMARY="ghcr.io/${{ github.repository_owner }}/sbcl-base:latest"
          OFFICIAL="ghcr.io/coalton-lang/sbcl-base:latest"
          if docker manifest inspect $PRIMARY > /dev/null 2>&1; then
            echo Will use PRIMARY image $PRIMARY >&2
            echo "image_repo_name=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
          else # Note - for some reason I cannot pull the image from coalton-lang
            if docker manifest inspect $OFFICIAL > /dev/null 2>&1; then
              echo Failed to access PRIMARY image $PRIMARY >&2
              echo Instead will use OFFICIAL image $OFFICIAL >&2
              echo "image_repo_name=coalton-lang" >> $GITHUB_OUTPUT
            else
              echo Failed to access OFFICIAL image $OFFICIAL >&2
              exit 1
            fi
          fi
          echo repo_name="${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest

    needs: check-image

    strategy:
      fail-fast: false
      matrix:
        LISP_IMPL: ["sbcl", "allegro", "ccl"]
        COALTON_ENV: ["release", "development"]
        SAFETY: ["0", "3"]
        DISABLE_SPECIALIZATION: ["1", "0"]
        HEURISTIC_INLINING: ["1", "0"]
        exclude:
          # Since we don't have a way of switching safety on allegro or ccl, we can
          # just ignore high safety tests.
          - LISP_IMPL: "allegro"
            # SAFETY: "3" # un-comment this line once the allegro license is renewed.
          - LISP_IMPL: "ccl"
            SAFETY: "3"

    permissions:
      packages: read

    container:
      image: ghcr.io/${{ needs.check-image.outputs.image_repo_name }}/${{ matrix.LISP_IMPL }}-base
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        # Tell ASDF to look through our repo recursively
        # See https://github.com/actions/runner/issues/2058
        # CL_SOURCE_REGISTRY: "${{ github.workspace }}//"
        CL_SOURCE_REGISTRY: "/__w/${{ needs.check-image.outputs.repo_name }}/${{ needs.check-image.outputs.repo_name }}//"

    steps:
      - uses: actions/checkout@v3
      - name: Run SBCL tests
        if: matrix.LISP_IMPL == 'sbcl'
        env:
          COALTON_ENV: ${{ matrix.COALTON_ENV }}
          COALTON_DISABLE_SPECIALIZATION: ${{ matrix.DISABLE_SPECIALIZATION }}
          COALTON_HEURISTIC_INLINING: ${{ matrix.HEURISTIC_INLINING }}
        run: |
          cat <<EOF > run-tests.lisp
          (sb-ext:restrict-compiler-policy 'safety ${{ matrix.SAFETY }})
          (ql:quickload :coalton/tests)
          (asdf:test-system :coalton/tests)
          ; TODO: Remove this or add tests for these programs.
          (asdf:load-system :small-coalton-programs)
          EOF
          sbcl --dynamic-space-size 2048 --non-interactive --load run-tests.lisp
      - name: Run Allegro CL tests
        if: matrix.LISP_IMPL == 'allegro'
        env:
          COALTON_ENV: ${{ matrix.COALTON_ENV }}
          COALTON_DISABLE_SPECIALIZATION: ${{ matrix.DISABLE_SPECIALIZATION }}
          COALTON_HEURISTIC_INLINING: ${{ matrix.HEURISTIC_INLINING }}
        run: |
          cat <<EOF > run-tests.lisp
          (ql:quickload :coalton/tests)
          (asdf:test-system :coalton/tests)
          ; TODO: Remove this or add tests for these programs.
          (asdf:load-system :small-coalton-programs)
          EOF
          cat run-tests.lisp | alisp --batch
      - name: Run Clozure CL tests
        if: matrix.LISP_IMPL == 'ccl'
        env:
          COALTON_ENV: ${{ matrix.COALTON_ENV }}
          COALTON_DISABLE_SPECIALIZATION: ${{ matrix.DISABLE_SPECIALIZATION }}
          COALTON_HEURISTIC_INLINING: ${{ matrix.HEURISTIC_INLINING }}
        run: |
          cat <<EOF > run-tests.lisp
          (cl:handler-case
            (cl:progn
          ;; This must be set before loading Coalton.
          (setf (get :coalton-config :emit-type-annotations) nil)
          (ql:quickload :coalton/tests)
          (asdf:test-system :coalton/tests)
          ; TODO: Remove this or add tests for these programs.
          (asdf:load-system :small-coalton-programs)
              (uiop:quit 0))
            (cl:error (c)
              (declare (ignore c))
              (uiop:quit 1)))
          EOF
          ccl64-wrapped.sh --batch --load run-tests.lisp
