name: Porting (2 abcl, ecl, clasp)

on:
  push:
    branches: [ "compat-in-small-pieces" ]
  pull_request:
    branches: [ "compat-in-small-pieces" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        LISP_IMPL: [ "abcl", "clasp", "ecl" ]
        COALTON_ENV: ["release", "development"]
        SAFETY: ["0", "3"]
        DISABLE_SPECIALIZATION: ["1", "0"]
        HEURISTIC_INLINING: ["1", "0"]
        exclude:
          # Since we don't have a way of switching safety on clasp or ecl, we can
          # just ignore high safety tests.
          - LISP_IMPL: "clasp"
            SAFETY: "3"
          - LISP_IMPL: "ecl"
            SAFETY: "3"

    permissions:
      packages: read

    container:
      image: ghcr.io/${{ github.repository_owner }}/${{ matrix.LISP_IMPL }}-port
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        # Tell ASDF to look through our repo recursively
        # See https://github.com/actions/runner/issues/2058
        CL_SOURCE_REGISTRY: "/__w/coalton-compat/coalton-compat//"

    steps:
      - uses: actions/checkout@v3
      - name: Run ABCL tests
        if: matrix.LISP_IMPL == 'abcl'
        env:
          COALTON_ENV: ${{ matrix.COALTON_ENV }}
          COALTON_DISABLE_SPECIALIZATION: ${{ matrix.DISABLE_SPECIALIZATION }}
          COALTON_HEURISTIC_INLINING: ${{ matrix.HEURISTIC_INLINING }}
        run: |
          cat <<EOF > run-tests.lisp
          (load "/.abclrc")
            ;; Ensure fiasco is patched in abcl
            (ql:quickload :fiasco) (load "compat/abcl-fiasco-patch")
          (setq system:*safety* ${{ matrix.SAFETY }})
          (ql:quickload :coalton/tests)
          (asdf:test-system :coalton/tests)
          ; TODO: Remove this or add tests for these programs.
          (asdf:load-system :small-coalton-programs)
          EOF
          abcl --noinform --noinit --nosystem --batch --load run-tests.lisp < /dev/null
      - name: Run Clasp tests
        if: matrix.LISP_IMPL == 'clasp'
        env:
          COALTON_ENV: ${{ matrix.COALTON_ENV }}
          COALTON_DISABLE_SPECIALIZATION: ${{ matrix.DISABLE_SPECIALIZATION }}
          COALTON_HEURISTIC_INLINING: ${{ matrix.HEURISTIC_INLINING }}
        run: |
          cat <<EOF > run-tests.lisp
          ;;; Clasp cannot find /.clasprc - copy its code here instead.
          ;; (load "/.clasprc")
            #-quicklisp (load "/root/quicklisp/setup.lisp")
            (setf ql:*local-project-directories* (quote ("/extras" "/lisp")))
          (ql:quickload :coalton/tests)
          (asdf:test-system :coalton/tests)
          ; TODO: Remove this or add tests for these programs.
          (asdf:load-system :small-coalton-programs)
          EOF
          clasp --script run-tests.lisp
      - name: Run ECL tests
        if: matrix.LISP_IMPL == 'ecl'
        env:
          COALTON_ENV: ${{ matrix.COALTON_ENV }}
          COALTON_DISABLE_SPECIALIZATION: ${{ matrix.DISABLE_SPECIALIZATION }}
          COALTON_HEURISTIC_INLINING: ${{ matrix.HEURISTIC_INLINING }}
        run: |
          cat <<EOF > run-tests.lisp
          (load "/.eclrc")
          (ql:quickload :coalton/tests)
          (asdf:test-system :coalton/tests)
          ; TODO: Remove this or add tests for these programs.
          (asdf:load-system :small-coalton-programs)
          EOF
          ecl --norc -q --shell run-tests.lisp
